package com.pckeiba.entity;

import java.util.Date;

public class IpatTohyoRireki {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.INSERT_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private Date insertTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.UPDATE_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.RECORD_SHUBETSU_ID
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String recordShubetsuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.DATA_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String dataKubun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.DATA_SAKUSEI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private Date dataSakuseiNengappi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.RACE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String raceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.KAISAI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private Date kaisaiNengappi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.KEIBAJO_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String keibajoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.KAISAI_KAIJI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private Short kaisaiKaiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.KAISAI_NICHIJI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private Short kaisaiNichiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.RACE_BANGO
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private Short raceBango;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.HOSHIKI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String hoshiki;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.SHIKIBETSU
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String shikibetsu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.KUMIBAN1
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String kumiban1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.KUMIBAN2
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String kumiban2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.KUMIBAN3
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String kumiban3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.WAKUREN_KUMIBAN1
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String wakurenKumiban1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.WAKUREN_KUMIBAN2
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String wakurenKumiban2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.TOHYO_MAISU
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private Short tohyoMaisu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.UKETSUKE_BANGO
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String uketsukeBango;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipat_tohyo_rireki.UKETSUKE_JIKOKU
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    private String uketsukeJikoku;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.INSERT_TIMESTAMP
     *
     * @return the value of ipat_tohyo_rireki.INSERT_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public Date getInsertTimestamp() {
        return insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.INSERT_TIMESTAMP
     *
     * @param insertTimestamp the value for ipat_tohyo_rireki.INSERT_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setInsertTimestamp(Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.UPDATE_TIMESTAMP
     *
     * @return the value of ipat_tohyo_rireki.UPDATE_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for ipat_tohyo_rireki.UPDATE_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.RECORD_SHUBETSU_ID
     *
     * @return the value of ipat_tohyo_rireki.RECORD_SHUBETSU_ID
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getRecordShubetsuId() {
        return recordShubetsuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.RECORD_SHUBETSU_ID
     *
     * @param recordShubetsuId the value for ipat_tohyo_rireki.RECORD_SHUBETSU_ID
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setRecordShubetsuId(String recordShubetsuId) {
        this.recordShubetsuId = recordShubetsuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.DATA_KUBUN
     *
     * @return the value of ipat_tohyo_rireki.DATA_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getDataKubun() {
        return dataKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.DATA_KUBUN
     *
     * @param dataKubun the value for ipat_tohyo_rireki.DATA_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setDataKubun(String dataKubun) {
        this.dataKubun = dataKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.DATA_SAKUSEI_NENGAPPI
     *
     * @return the value of ipat_tohyo_rireki.DATA_SAKUSEI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public Date getDataSakuseiNengappi() {
        return dataSakuseiNengappi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.DATA_SAKUSEI_NENGAPPI
     *
     * @param dataSakuseiNengappi the value for ipat_tohyo_rireki.DATA_SAKUSEI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setDataSakuseiNengappi(Date dataSakuseiNengappi) {
        this.dataSakuseiNengappi = dataSakuseiNengappi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.RACE_CODE
     *
     * @return the value of ipat_tohyo_rireki.RACE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getRaceCode() {
        return raceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.RACE_CODE
     *
     * @param raceCode the value for ipat_tohyo_rireki.RACE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setRaceCode(String raceCode) {
        this.raceCode = raceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.KAISAI_NENGAPPI
     *
     * @return the value of ipat_tohyo_rireki.KAISAI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public Date getKaisaiNengappi() {
        return kaisaiNengappi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.KAISAI_NENGAPPI
     *
     * @param kaisaiNengappi the value for ipat_tohyo_rireki.KAISAI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setKaisaiNengappi(Date kaisaiNengappi) {
        this.kaisaiNengappi = kaisaiNengappi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.KEIBAJO_CODE
     *
     * @return the value of ipat_tohyo_rireki.KEIBAJO_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getKeibajoCode() {
        return keibajoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.KEIBAJO_CODE
     *
     * @param keibajoCode the value for ipat_tohyo_rireki.KEIBAJO_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setKeibajoCode(String keibajoCode) {
        this.keibajoCode = keibajoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.KAISAI_KAIJI
     *
     * @return the value of ipat_tohyo_rireki.KAISAI_KAIJI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public Short getKaisaiKaiji() {
        return kaisaiKaiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.KAISAI_KAIJI
     *
     * @param kaisaiKaiji the value for ipat_tohyo_rireki.KAISAI_KAIJI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setKaisaiKaiji(Short kaisaiKaiji) {
        this.kaisaiKaiji = kaisaiKaiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.KAISAI_NICHIJI
     *
     * @return the value of ipat_tohyo_rireki.KAISAI_NICHIJI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public Short getKaisaiNichiji() {
        return kaisaiNichiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.KAISAI_NICHIJI
     *
     * @param kaisaiNichiji the value for ipat_tohyo_rireki.KAISAI_NICHIJI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setKaisaiNichiji(Short kaisaiNichiji) {
        this.kaisaiNichiji = kaisaiNichiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.RACE_BANGO
     *
     * @return the value of ipat_tohyo_rireki.RACE_BANGO
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public Short getRaceBango() {
        return raceBango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.RACE_BANGO
     *
     * @param raceBango the value for ipat_tohyo_rireki.RACE_BANGO
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setRaceBango(Short raceBango) {
        this.raceBango = raceBango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.HOSHIKI
     *
     * @return the value of ipat_tohyo_rireki.HOSHIKI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getHoshiki() {
        return hoshiki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.HOSHIKI
     *
     * @param hoshiki the value for ipat_tohyo_rireki.HOSHIKI
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setHoshiki(String hoshiki) {
        this.hoshiki = hoshiki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.SHIKIBETSU
     *
     * @return the value of ipat_tohyo_rireki.SHIKIBETSU
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getShikibetsu() {
        return shikibetsu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.SHIKIBETSU
     *
     * @param shikibetsu the value for ipat_tohyo_rireki.SHIKIBETSU
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setShikibetsu(String shikibetsu) {
        this.shikibetsu = shikibetsu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.KUMIBAN1
     *
     * @return the value of ipat_tohyo_rireki.KUMIBAN1
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getKumiban1() {
        return kumiban1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.KUMIBAN1
     *
     * @param kumiban1 the value for ipat_tohyo_rireki.KUMIBAN1
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setKumiban1(String kumiban1) {
        this.kumiban1 = kumiban1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.KUMIBAN2
     *
     * @return the value of ipat_tohyo_rireki.KUMIBAN2
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getKumiban2() {
        return kumiban2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.KUMIBAN2
     *
     * @param kumiban2 the value for ipat_tohyo_rireki.KUMIBAN2
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setKumiban2(String kumiban2) {
        this.kumiban2 = kumiban2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.KUMIBAN3
     *
     * @return the value of ipat_tohyo_rireki.KUMIBAN3
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getKumiban3() {
        return kumiban3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.KUMIBAN3
     *
     * @param kumiban3 the value for ipat_tohyo_rireki.KUMIBAN3
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setKumiban3(String kumiban3) {
        this.kumiban3 = kumiban3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.WAKUREN_KUMIBAN1
     *
     * @return the value of ipat_tohyo_rireki.WAKUREN_KUMIBAN1
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getWakurenKumiban1() {
        return wakurenKumiban1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.WAKUREN_KUMIBAN1
     *
     * @param wakurenKumiban1 the value for ipat_tohyo_rireki.WAKUREN_KUMIBAN1
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setWakurenKumiban1(String wakurenKumiban1) {
        this.wakurenKumiban1 = wakurenKumiban1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.WAKUREN_KUMIBAN2
     *
     * @return the value of ipat_tohyo_rireki.WAKUREN_KUMIBAN2
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getWakurenKumiban2() {
        return wakurenKumiban2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.WAKUREN_KUMIBAN2
     *
     * @param wakurenKumiban2 the value for ipat_tohyo_rireki.WAKUREN_KUMIBAN2
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setWakurenKumiban2(String wakurenKumiban2) {
        this.wakurenKumiban2 = wakurenKumiban2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.TOHYO_MAISU
     *
     * @return the value of ipat_tohyo_rireki.TOHYO_MAISU
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public Short getTohyoMaisu() {
        return tohyoMaisu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.TOHYO_MAISU
     *
     * @param tohyoMaisu the value for ipat_tohyo_rireki.TOHYO_MAISU
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setTohyoMaisu(Short tohyoMaisu) {
        this.tohyoMaisu = tohyoMaisu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.UKETSUKE_BANGO
     *
     * @return the value of ipat_tohyo_rireki.UKETSUKE_BANGO
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getUketsukeBango() {
        return uketsukeBango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.UKETSUKE_BANGO
     *
     * @param uketsukeBango the value for ipat_tohyo_rireki.UKETSUKE_BANGO
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setUketsukeBango(String uketsukeBango) {
        this.uketsukeBango = uketsukeBango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipat_tohyo_rireki.UKETSUKE_JIKOKU
     *
     * @return the value of ipat_tohyo_rireki.UKETSUKE_JIKOKU
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getUketsukeJikoku() {
        return uketsukeJikoku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipat_tohyo_rireki.UKETSUKE_JIKOKU
     *
     * @param uketsukeJikoku the value for ipat_tohyo_rireki.UKETSUKE_JIKOKU
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setUketsukeJikoku(String uketsukeJikoku) {
        this.uketsukeJikoku = uketsukeJikoku;
    }
}