package com.pckeiba.entity;

import com.pckeiba.entity.JvdBanushiSeiseki;
import com.pckeiba.entity.JvdBanushiSeisekiExample;
import com.pckeiba.entity.JvdBanushiSeisekiKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdBanushiSeisekiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdBanushiSeisekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdBanushiSeisekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdBanushiSeisekiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdBanushiSeiseki record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdBanushiSeiseki record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdBanushiSeiseki> selectByExample(JvdBanushiSeisekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdBanushiSeiseki selectByPrimaryKey(JvdBanushiSeisekiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdBanushiSeiseki record, @Param("example") JvdBanushiSeisekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdBanushiSeiseki record, @Param("example") JvdBanushiSeisekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdBanushiSeiseki record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_banushi_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdBanushiSeiseki record);
}