package com.pckeiba.entity;

import com.pckeiba.entity.JvdChokyoshiMaster;
import com.pckeiba.entity.JvdChokyoshiMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdChokyoshiMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdChokyoshiMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdChokyoshiMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(String chokyoshiCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdChokyoshiMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdChokyoshiMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdChokyoshiMaster> selectByExample(JvdChokyoshiMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdChokyoshiMaster selectByPrimaryKey(String chokyoshiCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdChokyoshiMaster record, @Param("example") JvdChokyoshiMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdChokyoshiMaster record, @Param("example") JvdChokyoshiMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdChokyoshiMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdChokyoshiMaster record);
}