package com.pckeiba.entity;

import com.pckeiba.entity.JvdChokyoshiShussobetsu2;
import com.pckeiba.entity.JvdChokyoshiShussobetsu2Example;
import com.pckeiba.entity.JvdChokyoshiShussobetsu2Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdChokyoshiShussobetsu2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdChokyoshiShussobetsu2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdChokyoshiShussobetsu2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdChokyoshiShussobetsu2Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdChokyoshiShussobetsu2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdChokyoshiShussobetsu2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdChokyoshiShussobetsu2> selectByExample(JvdChokyoshiShussobetsu2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdChokyoshiShussobetsu2 selectByPrimaryKey(JvdChokyoshiShussobetsu2Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdChokyoshiShussobetsu2 record, @Param("example") JvdChokyoshiShussobetsu2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdChokyoshiShussobetsu2 record, @Param("example") JvdChokyoshiShussobetsu2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdChokyoshiShussobetsu2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_chokyoshi_shussobetsu2
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdChokyoshiShussobetsu2 record);
}