package com.pckeiba.entity;

import com.pckeiba.entity.JvdDataMiningYoso;
import com.pckeiba.entity.JvdDataMiningYosoExample;
import com.pckeiba.entity.JvdDataMiningYosoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdDataMiningYosoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdDataMiningYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdDataMiningYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdDataMiningYosoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdDataMiningYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdDataMiningYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdDataMiningYoso> selectByExample(JvdDataMiningYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdDataMiningYoso selectByPrimaryKey(JvdDataMiningYosoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdDataMiningYoso record, @Param("example") JvdDataMiningYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdDataMiningYoso record, @Param("example") JvdDataMiningYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdDataMiningYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_data_mining_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdDataMiningYoso record);
}