package com.pckeiba.entity;

import com.pckeiba.entity.JvdGaibuShisu;
import com.pckeiba.entity.JvdGaibuShisuExample;
import com.pckeiba.entity.JvdGaibuShisuKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdGaibuShisuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdGaibuShisuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdGaibuShisuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdGaibuShisuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdGaibuShisu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdGaibuShisu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdGaibuShisu> selectByExample(JvdGaibuShisuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdGaibuShisu selectByPrimaryKey(JvdGaibuShisuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdGaibuShisu record, @Param("example") JvdGaibuShisuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdGaibuShisu record, @Param("example") JvdGaibuShisuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdGaibuShisu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_gaibu_shisu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdGaibuShisu record);
}