package com.pckeiba.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JvdHanroChokyoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public JvdHanroChokyoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChokyoJikokuIsNull() {
            addCriterion("CHOKYO_JIKOKU is null");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuIsNotNull() {
            addCriterion("CHOKYO_JIKOKU is not null");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuEqualTo(Date value) {
            addCriterion("CHOKYO_JIKOKU =", value, "chokyoJikoku");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuNotEqualTo(Date value) {
            addCriterion("CHOKYO_JIKOKU <>", value, "chokyoJikoku");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuGreaterThan(Date value) {
            addCriterion("CHOKYO_JIKOKU >", value, "chokyoJikoku");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuGreaterThanOrEqualTo(Date value) {
            addCriterion("CHOKYO_JIKOKU >=", value, "chokyoJikoku");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuLessThan(Date value) {
            addCriterion("CHOKYO_JIKOKU <", value, "chokyoJikoku");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuLessThanOrEqualTo(Date value) {
            addCriterion("CHOKYO_JIKOKU <=", value, "chokyoJikoku");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuIn(List<Date> values) {
            addCriterion("CHOKYO_JIKOKU in", values, "chokyoJikoku");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuNotIn(List<Date> values) {
            addCriterion("CHOKYO_JIKOKU not in", values, "chokyoJikoku");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuBetween(Date value1, Date value2) {
            addCriterion("CHOKYO_JIKOKU between", value1, value2, "chokyoJikoku");
            return (Criteria) this;
        }

        public Criteria andChokyoJikokuNotBetween(Date value1, Date value2) {
            addCriterion("CHOKYO_JIKOKU not between", value1, value2, "chokyoJikoku");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoIsNull() {
            addCriterion("KETTO_TOROKU_BANGO is null");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoIsNotNull() {
            addCriterion("KETTO_TOROKU_BANGO is not null");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoEqualTo(String value) {
            addCriterion("KETTO_TOROKU_BANGO =", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoNotEqualTo(String value) {
            addCriterion("KETTO_TOROKU_BANGO <>", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoGreaterThan(String value) {
            addCriterion("KETTO_TOROKU_BANGO >", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoGreaterThanOrEqualTo(String value) {
            addCriterion("KETTO_TOROKU_BANGO >=", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoLessThan(String value) {
            addCriterion("KETTO_TOROKU_BANGO <", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoLessThanOrEqualTo(String value) {
            addCriterion("KETTO_TOROKU_BANGO <=", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoLike(String value) {
            addCriterion("KETTO_TOROKU_BANGO like", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoNotLike(String value) {
            addCriterion("KETTO_TOROKU_BANGO not like", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoIn(List<String> values) {
            addCriterion("KETTO_TOROKU_BANGO in", values, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoNotIn(List<String> values) {
            addCriterion("KETTO_TOROKU_BANGO not in", values, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoBetween(String value1, String value2) {
            addCriterion("KETTO_TOROKU_BANGO between", value1, value2, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoNotBetween(String value1, String value2) {
            addCriterion("KETTO_TOROKU_BANGO not between", value1, value2, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andTracenKubunIsNull() {
            addCriterion("TRACEN_KUBUN is null");
            return (Criteria) this;
        }

        public Criteria andTracenKubunIsNotNull() {
            addCriterion("TRACEN_KUBUN is not null");
            return (Criteria) this;
        }

        public Criteria andTracenKubunEqualTo(String value) {
            addCriterion("TRACEN_KUBUN =", value, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunNotEqualTo(String value) {
            addCriterion("TRACEN_KUBUN <>", value, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunGreaterThan(String value) {
            addCriterion("TRACEN_KUBUN >", value, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunGreaterThanOrEqualTo(String value) {
            addCriterion("TRACEN_KUBUN >=", value, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunLessThan(String value) {
            addCriterion("TRACEN_KUBUN <", value, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunLessThanOrEqualTo(String value) {
            addCriterion("TRACEN_KUBUN <=", value, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunLike(String value) {
            addCriterion("TRACEN_KUBUN like", value, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunNotLike(String value) {
            addCriterion("TRACEN_KUBUN not like", value, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunIn(List<String> values) {
            addCriterion("TRACEN_KUBUN in", values, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunNotIn(List<String> values) {
            addCriterion("TRACEN_KUBUN not in", values, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunBetween(String value1, String value2) {
            addCriterion("TRACEN_KUBUN between", value1, value2, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andTracenKubunNotBetween(String value1, String value2) {
            addCriterion("TRACEN_KUBUN not between", value1, value2, "tracenKubun");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampIsNull() {
            addCriterion("INSERT_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampIsNotNull() {
            addCriterion("INSERT_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampEqualTo(Date value) {
            addCriterion("INSERT_TIMESTAMP =", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampNotEqualTo(Date value) {
            addCriterion("INSERT_TIMESTAMP <>", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampGreaterThan(Date value) {
            addCriterion("INSERT_TIMESTAMP >", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERT_TIMESTAMP >=", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampLessThan(Date value) {
            addCriterion("INSERT_TIMESTAMP <", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampLessThanOrEqualTo(Date value) {
            addCriterion("INSERT_TIMESTAMP <=", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampIn(List<Date> values) {
            addCriterion("INSERT_TIMESTAMP in", values, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampNotIn(List<Date> values) {
            addCriterion("INSERT_TIMESTAMP not in", values, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampBetween(Date value1, Date value2) {
            addCriterion("INSERT_TIMESTAMP between", value1, value2, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampNotBetween(Date value1, Date value2) {
            addCriterion("INSERT_TIMESTAMP not between", value1, value2, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("UPDATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("UPDATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdIsNull() {
            addCriterion("RECORD_SHUBETSU_ID is null");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdIsNotNull() {
            addCriterion("RECORD_SHUBETSU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdEqualTo(String value) {
            addCriterion("RECORD_SHUBETSU_ID =", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdNotEqualTo(String value) {
            addCriterion("RECORD_SHUBETSU_ID <>", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdGreaterThan(String value) {
            addCriterion("RECORD_SHUBETSU_ID >", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdGreaterThanOrEqualTo(String value) {
            addCriterion("RECORD_SHUBETSU_ID >=", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdLessThan(String value) {
            addCriterion("RECORD_SHUBETSU_ID <", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdLessThanOrEqualTo(String value) {
            addCriterion("RECORD_SHUBETSU_ID <=", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdLike(String value) {
            addCriterion("RECORD_SHUBETSU_ID like", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdNotLike(String value) {
            addCriterion("RECORD_SHUBETSU_ID not like", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdIn(List<String> values) {
            addCriterion("RECORD_SHUBETSU_ID in", values, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdNotIn(List<String> values) {
            addCriterion("RECORD_SHUBETSU_ID not in", values, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdBetween(String value1, String value2) {
            addCriterion("RECORD_SHUBETSU_ID between", value1, value2, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdNotBetween(String value1, String value2) {
            addCriterion("RECORD_SHUBETSU_ID not between", value1, value2, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andDataKubunIsNull() {
            addCriterion("DATA_KUBUN is null");
            return (Criteria) this;
        }

        public Criteria andDataKubunIsNotNull() {
            addCriterion("DATA_KUBUN is not null");
            return (Criteria) this;
        }

        public Criteria andDataKubunEqualTo(String value) {
            addCriterion("DATA_KUBUN =", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotEqualTo(String value) {
            addCriterion("DATA_KUBUN <>", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunGreaterThan(String value) {
            addCriterion("DATA_KUBUN >", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_KUBUN >=", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunLessThan(String value) {
            addCriterion("DATA_KUBUN <", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunLessThanOrEqualTo(String value) {
            addCriterion("DATA_KUBUN <=", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunLike(String value) {
            addCriterion("DATA_KUBUN like", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotLike(String value) {
            addCriterion("DATA_KUBUN not like", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunIn(List<String> values) {
            addCriterion("DATA_KUBUN in", values, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotIn(List<String> values) {
            addCriterion("DATA_KUBUN not in", values, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunBetween(String value1, String value2) {
            addCriterion("DATA_KUBUN between", value1, value2, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotBetween(String value1, String value2) {
            addCriterion("DATA_KUBUN not between", value1, value2, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiIsNull() {
            addCriterion("DATA_SAKUSEI_NENGAPPI is null");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiIsNotNull() {
            addCriterion("DATA_SAKUSEI_NENGAPPI is not null");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiEqualTo(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI =", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiNotEqualTo(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI <>", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiGreaterThan(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI >", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiGreaterThanOrEqualTo(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI >=", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiLessThan(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI <", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiLessThanOrEqualTo(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI <=", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiIn(List<Date> values) {
            addCriterion("DATA_SAKUSEI_NENGAPPI in", values, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiNotIn(List<Date> values) {
            addCriterion("DATA_SAKUSEI_NENGAPPI not in", values, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiBetween(Date value1, Date value2) {
            addCriterion("DATA_SAKUSEI_NENGAPPI between", value1, value2, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiNotBetween(Date value1, Date value2) {
            addCriterion("DATA_SAKUSEI_NENGAPPI not between", value1, value2, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongIsNull() {
            addCriterion("TIME_GOKEI_4FURLONG is null");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongIsNotNull() {
            addCriterion("TIME_GOKEI_4FURLONG is not null");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_4FURLONG =", value, "timeGokei4furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongNotEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_4FURLONG <>", value, "timeGokei4furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongGreaterThan(BigDecimal value) {
            addCriterion("TIME_GOKEI_4FURLONG >", value, "timeGokei4furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_4FURLONG >=", value, "timeGokei4furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongLessThan(BigDecimal value) {
            addCriterion("TIME_GOKEI_4FURLONG <", value, "timeGokei4furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_4FURLONG <=", value, "timeGokei4furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongIn(List<BigDecimal> values) {
            addCriterion("TIME_GOKEI_4FURLONG in", values, "timeGokei4furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongNotIn(List<BigDecimal> values) {
            addCriterion("TIME_GOKEI_4FURLONG not in", values, "timeGokei4furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TIME_GOKEI_4FURLONG between", value1, value2, "timeGokei4furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei4furlongNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TIME_GOKEI_4FURLONG not between", value1, value2, "timeGokei4furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongIsNull() {
            addCriterion("LAP_TIME_4FURLONG is null");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongIsNotNull() {
            addCriterion("LAP_TIME_4FURLONG is not null");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_4FURLONG =", value, "lapTime4furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongNotEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_4FURLONG <>", value, "lapTime4furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongGreaterThan(BigDecimal value) {
            addCriterion("LAP_TIME_4FURLONG >", value, "lapTime4furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_4FURLONG >=", value, "lapTime4furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongLessThan(BigDecimal value) {
            addCriterion("LAP_TIME_4FURLONG <", value, "lapTime4furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_4FURLONG <=", value, "lapTime4furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongIn(List<BigDecimal> values) {
            addCriterion("LAP_TIME_4FURLONG in", values, "lapTime4furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongNotIn(List<BigDecimal> values) {
            addCriterion("LAP_TIME_4FURLONG not in", values, "lapTime4furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAP_TIME_4FURLONG between", value1, value2, "lapTime4furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime4furlongNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAP_TIME_4FURLONG not between", value1, value2, "lapTime4furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongIsNull() {
            addCriterion("TIME_GOKEI_3FURLONG is null");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongIsNotNull() {
            addCriterion("TIME_GOKEI_3FURLONG is not null");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_3FURLONG =", value, "timeGokei3furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongNotEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_3FURLONG <>", value, "timeGokei3furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongGreaterThan(BigDecimal value) {
            addCriterion("TIME_GOKEI_3FURLONG >", value, "timeGokei3furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_3FURLONG >=", value, "timeGokei3furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongLessThan(BigDecimal value) {
            addCriterion("TIME_GOKEI_3FURLONG <", value, "timeGokei3furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_3FURLONG <=", value, "timeGokei3furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongIn(List<BigDecimal> values) {
            addCriterion("TIME_GOKEI_3FURLONG in", values, "timeGokei3furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongNotIn(List<BigDecimal> values) {
            addCriterion("TIME_GOKEI_3FURLONG not in", values, "timeGokei3furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TIME_GOKEI_3FURLONG between", value1, value2, "timeGokei3furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei3furlongNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TIME_GOKEI_3FURLONG not between", value1, value2, "timeGokei3furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongIsNull() {
            addCriterion("LAP_TIME_3FURLONG is null");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongIsNotNull() {
            addCriterion("LAP_TIME_3FURLONG is not null");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_3FURLONG =", value, "lapTime3furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongNotEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_3FURLONG <>", value, "lapTime3furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongGreaterThan(BigDecimal value) {
            addCriterion("LAP_TIME_3FURLONG >", value, "lapTime3furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_3FURLONG >=", value, "lapTime3furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongLessThan(BigDecimal value) {
            addCriterion("LAP_TIME_3FURLONG <", value, "lapTime3furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_3FURLONG <=", value, "lapTime3furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongIn(List<BigDecimal> values) {
            addCriterion("LAP_TIME_3FURLONG in", values, "lapTime3furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongNotIn(List<BigDecimal> values) {
            addCriterion("LAP_TIME_3FURLONG not in", values, "lapTime3furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAP_TIME_3FURLONG between", value1, value2, "lapTime3furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime3furlongNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAP_TIME_3FURLONG not between", value1, value2, "lapTime3furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongIsNull() {
            addCriterion("TIME_GOKEI_2FURLONG is null");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongIsNotNull() {
            addCriterion("TIME_GOKEI_2FURLONG is not null");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_2FURLONG =", value, "timeGokei2furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongNotEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_2FURLONG <>", value, "timeGokei2furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongGreaterThan(BigDecimal value) {
            addCriterion("TIME_GOKEI_2FURLONG >", value, "timeGokei2furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_2FURLONG >=", value, "timeGokei2furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongLessThan(BigDecimal value) {
            addCriterion("TIME_GOKEI_2FURLONG <", value, "timeGokei2furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TIME_GOKEI_2FURLONG <=", value, "timeGokei2furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongIn(List<BigDecimal> values) {
            addCriterion("TIME_GOKEI_2FURLONG in", values, "timeGokei2furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongNotIn(List<BigDecimal> values) {
            addCriterion("TIME_GOKEI_2FURLONG not in", values, "timeGokei2furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TIME_GOKEI_2FURLONG between", value1, value2, "timeGokei2furlong");
            return (Criteria) this;
        }

        public Criteria andTimeGokei2furlongNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TIME_GOKEI_2FURLONG not between", value1, value2, "timeGokei2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongIsNull() {
            addCriterion("LAP_TIME_2FURLONG is null");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongIsNotNull() {
            addCriterion("LAP_TIME_2FURLONG is not null");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_2FURLONG =", value, "lapTime2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongNotEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_2FURLONG <>", value, "lapTime2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongGreaterThan(BigDecimal value) {
            addCriterion("LAP_TIME_2FURLONG >", value, "lapTime2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_2FURLONG >=", value, "lapTime2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongLessThan(BigDecimal value) {
            addCriterion("LAP_TIME_2FURLONG <", value, "lapTime2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_2FURLONG <=", value, "lapTime2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongIn(List<BigDecimal> values) {
            addCriterion("LAP_TIME_2FURLONG in", values, "lapTime2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongNotIn(List<BigDecimal> values) {
            addCriterion("LAP_TIME_2FURLONG not in", values, "lapTime2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAP_TIME_2FURLONG between", value1, value2, "lapTime2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime2furlongNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAP_TIME_2FURLONG not between", value1, value2, "lapTime2furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongIsNull() {
            addCriterion("LAP_TIME_1FURLONG is null");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongIsNotNull() {
            addCriterion("LAP_TIME_1FURLONG is not null");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_1FURLONG =", value, "lapTime1furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongNotEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_1FURLONG <>", value, "lapTime1furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongGreaterThan(BigDecimal value) {
            addCriterion("LAP_TIME_1FURLONG >", value, "lapTime1furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_1FURLONG >=", value, "lapTime1furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongLessThan(BigDecimal value) {
            addCriterion("LAP_TIME_1FURLONG <", value, "lapTime1furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAP_TIME_1FURLONG <=", value, "lapTime1furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongIn(List<BigDecimal> values) {
            addCriterion("LAP_TIME_1FURLONG in", values, "lapTime1furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongNotIn(List<BigDecimal> values) {
            addCriterion("LAP_TIME_1FURLONG not in", values, "lapTime1furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAP_TIME_1FURLONG between", value1, value2, "lapTime1furlong");
            return (Criteria) this;
        }

        public Criteria andLapTime1furlongNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAP_TIME_1FURLONG not between", value1, value2, "lapTime1furlong");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Mon Apr 29 22:52:29 GMT+09:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}