package com.pckeiba.entity;

import com.pckeiba.entity.JvdHanroChokyo;
import com.pckeiba.entity.JvdHanroChokyoExample;
import com.pckeiba.entity.JvdHanroChokyoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdHanroChokyoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdHanroChokyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdHanroChokyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdHanroChokyoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdHanroChokyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdHanroChokyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdHanroChokyo> selectByExample(JvdHanroChokyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdHanroChokyo selectByPrimaryKey(JvdHanroChokyoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdHanroChokyo record, @Param("example") JvdHanroChokyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdHanroChokyo record, @Param("example") JvdHanroChokyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdHanroChokyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_hanro_chokyo
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdHanroChokyo record);
}