package com.pckeiba.entity;

import com.pckeiba.entity.JvdJikeiretsuWakurenOdds;
import com.pckeiba.entity.JvdJikeiretsuWakurenOddsExample;
import com.pckeiba.entity.JvdJikeiretsuWakurenOddsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdJikeiretsuWakurenOddsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdJikeiretsuWakurenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdJikeiretsuWakurenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdJikeiretsuWakurenOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdJikeiretsuWakurenOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdJikeiretsuWakurenOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdJikeiretsuWakurenOdds> selectByExample(JvdJikeiretsuWakurenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdJikeiretsuWakurenOdds selectByPrimaryKey(JvdJikeiretsuWakurenOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdJikeiretsuWakurenOdds record, @Param("example") JvdJikeiretsuWakurenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdJikeiretsuWakurenOdds record, @Param("example") JvdJikeiretsuWakurenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdJikeiretsuWakurenOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_wakuren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdJikeiretsuWakurenOdds record);
}