package com.pckeiba.entity;

import com.pckeiba.entity.JvdJikeiretsuTanpukuOdds;
import com.pckeiba.entity.JvdJikeiretsuTanpukuOddsExample;
import com.pckeiba.entity.JvdJikeiretsuTanpukuOddsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdJikeiretsuTanpukuOddsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdJikeiretsuTanpukuOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdJikeiretsuTanpukuOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdJikeiretsuTanpukuOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdJikeiretsuTanpukuOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdJikeiretsuTanpukuOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdJikeiretsuTanpukuOdds> selectByExample(JvdJikeiretsuTanpukuOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdJikeiretsuTanpukuOdds selectByPrimaryKey(JvdJikeiretsuTanpukuOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdJikeiretsuTanpukuOdds record, @Param("example") JvdJikeiretsuTanpukuOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdJikeiretsuTanpukuOdds record, @Param("example") JvdJikeiretsuTanpukuOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdJikeiretsuTanpukuOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_tanpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdJikeiretsuTanpukuOdds record);
}