package com.pckeiba.entity;

import com.pckeiba.entity.JvdJikeiretsuUmarenOdds;
import com.pckeiba.entity.JvdJikeiretsuUmarenOddsExample;
import com.pckeiba.entity.JvdJikeiretsuUmarenOddsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdJikeiretsuUmarenOddsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdJikeiretsuUmarenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdJikeiretsuUmarenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdJikeiretsuUmarenOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdJikeiretsuUmarenOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdJikeiretsuUmarenOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdJikeiretsuUmarenOdds> selectByExample(JvdJikeiretsuUmarenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdJikeiretsuUmarenOdds selectByPrimaryKey(JvdJikeiretsuUmarenOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdJikeiretsuUmarenOdds record, @Param("example") JvdJikeiretsuUmarenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdJikeiretsuUmarenOdds record, @Param("example") JvdJikeiretsuUmarenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdJikeiretsuUmarenOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_jikeiretsu_umaren_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdJikeiretsuUmarenOdds record);
}