package com.pckeiba.entity;

public class JvdKyosobaShussobetsu3Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_kyosoba_shussobetsu3.KETTO_TOROKU_BANGO
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    private String kettoTorokuBango;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_kyosoba_shussobetsu3.RACE_CODE
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    private String raceCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_kyosoba_shussobetsu3.KETTO_TOROKU_BANGO
     *
     * @return the value of jvd_kyosoba_shussobetsu3.KETTO_TOROKU_BANGO
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public String getKettoTorokuBango() {
        return kettoTorokuBango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_kyosoba_shussobetsu3.KETTO_TOROKU_BANGO
     *
     * @param kettoTorokuBango the value for jvd_kyosoba_shussobetsu3.KETTO_TOROKU_BANGO
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void setKettoTorokuBango(String kettoTorokuBango) {
        this.kettoTorokuBango = kettoTorokuBango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_kyosoba_shussobetsu3.RACE_CODE
     *
     * @return the value of jvd_kyosoba_shussobetsu3.RACE_CODE
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public String getRaceCode() {
        return raceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_kyosoba_shussobetsu3.RACE_CODE
     *
     * @param raceCode the value for jvd_kyosoba_shussobetsu3.RACE_CODE
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void setRaceCode(String raceCode) {
        this.raceCode = raceCode;
    }
}