package com.pckeiba.entity;

import com.pckeiba.entity.JvdKyosobaJogaiJoho;
import com.pckeiba.entity.JvdKyosobaJogaiJohoExample;
import com.pckeiba.entity.JvdKyosobaJogaiJohoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdKyosobaJogaiJohoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdKyosobaJogaiJohoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdKyosobaJogaiJohoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdKyosobaJogaiJohoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdKyosobaJogaiJoho record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdKyosobaJogaiJoho record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdKyosobaJogaiJoho> selectByExample(JvdKyosobaJogaiJohoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdKyosobaJogaiJoho selectByPrimaryKey(JvdKyosobaJogaiJohoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdKyosobaJogaiJoho record, @Param("example") JvdKyosobaJogaiJohoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdKyosobaJogaiJoho record, @Param("example") JvdKyosobaJogaiJohoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdKyosobaJogaiJoho record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_jogai_joho
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdKyosobaJogaiJoho record);
}