package com.pckeiba.entity;

import com.pckeiba.entity.JvdKyosobaTorihikiKakaku;
import com.pckeiba.entity.JvdKyosobaTorihikiKakakuExample;
import com.pckeiba.entity.JvdKyosobaTorihikiKakakuKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdKyosobaTorihikiKakakuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdKyosobaTorihikiKakakuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdKyosobaTorihikiKakakuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdKyosobaTorihikiKakakuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdKyosobaTorihikiKakaku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdKyosobaTorihikiKakaku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdKyosobaTorihikiKakaku> selectByExample(JvdKyosobaTorihikiKakakuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdKyosobaTorihikiKakaku selectByPrimaryKey(JvdKyosobaTorihikiKakakuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdKyosobaTorihikiKakaku record, @Param("example") JvdKyosobaTorihikiKakakuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdKyosobaTorihikiKakaku record, @Param("example") JvdKyosobaTorihikiKakakuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdKyosobaTorihikiKakaku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_torihiki_kakaku
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdKyosobaTorihikiKakaku record);
}