package com.pckeiba.entity;

import com.pckeiba.entity.JvdKishuHenko;
import com.pckeiba.entity.JvdKishuHenkoExample;
import com.pckeiba.entity.JvdKishuHenkoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdKishuHenkoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdKishuHenkoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdKishuHenkoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdKishuHenkoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdKishuHenko record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdKishuHenko record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdKishuHenko> selectByExample(JvdKishuHenkoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdKishuHenko selectByPrimaryKey(JvdKishuHenkoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdKishuHenko record, @Param("example") JvdKishuHenkoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdKishuHenko record, @Param("example") JvdKishuHenkoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdKishuHenko record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kishu_henko
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdKishuHenko record);
}