package com.pckeiba.entity;

import com.pckeiba.entity.JvdKyosobaShussobetsu1;
import com.pckeiba.entity.JvdKyosobaShussobetsu1Example;
import com.pckeiba.entity.JvdKyosobaShussobetsu1Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdKyosobaShussobetsu1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdKyosobaShussobetsu1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdKyosobaShussobetsu1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdKyosobaShussobetsu1Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdKyosobaShussobetsu1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdKyosobaShussobetsu1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdKyosobaShussobetsu1> selectByExample(JvdKyosobaShussobetsu1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdKyosobaShussobetsu1 selectByPrimaryKey(JvdKyosobaShussobetsu1Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdKyosobaShussobetsu1 record, @Param("example") JvdKyosobaShussobetsu1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdKyosobaShussobetsu1 record, @Param("example") JvdKyosobaShussobetsu1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdKyosobaShussobetsu1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_kyosoba_shussobetsu1
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdKyosobaShussobetsu1 record);
}