package com.pckeiba.entity;

public class JvdKishuSeisekiKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_kishu_seiseki.KISHU_CODE
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    private String kishuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_kishu_seiseki.SETTEI_NEN
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    private Short setteiNen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_kishu_seiseki.KISHU_CODE
     *
     * @return the value of jvd_kishu_seiseki.KISHU_CODE
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public String getKishuCode() {
        return kishuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_kishu_seiseki.KISHU_CODE
     *
     * @param kishuCode the value for jvd_kishu_seiseki.KISHU_CODE
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void setKishuCode(String kishuCode) {
        this.kishuCode = kishuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_kishu_seiseki.SETTEI_NEN
     *
     * @return the value of jvd_kishu_seiseki.SETTEI_NEN
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public Short getSetteiNen() {
        return setteiNen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_kishu_seiseki.SETTEI_NEN
     *
     * @param setteiNen the value for jvd_kishu_seiseki.SETTEI_NEN
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void setSetteiNen(Short setteiNen) {
        this.setteiNen = setteiNen;
    }
}