package com.pckeiba.entity;

import java.util.Date;

public class JvdOddsMasterYoso {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.RACE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String raceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.INSERT_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Date insertTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.UPDATE_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.RECORD_SHUBETSU_ID
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String recordShubetsuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.DATA_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String dataKubun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.DATA_SAKUSEI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Date dataSakuseiNengappi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KAISAI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Date kaisaiNengappi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KEIBAJO_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String keibajoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KAISAI_KAIJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Short kaisaiKaiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KAISAI_NICHIJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Short kaisaiNichiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.RACE_BANGO
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Short raceBango;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.YOBI_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String yobiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.CHUO_CHIHO_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String chuoChihoKubun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.IPPAN_TOKUBETSU_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String ippanTokubetsuKubun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.HEICHI_SHOGAI_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String heichiShogaiKubun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.JUSHO_KAIJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Short jushoKaiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KYOSOMEI_15MOJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String kyosomei15moji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KYOSOMEI_7MOJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String kyosomei7moji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.GRADE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String gradeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.JPN_FLAG
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String jpnFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.JURYO_SHUBETSU_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String juryoShubetsuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.JURYO_SHUBETSU_SHOSAI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String juryoShubetsuShosai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KYOSO_KIGO_CODE1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String kyosoKigoCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KYOSO_KIGO_CODE2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String kyosoKigoCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KYOSO_SHUBETSU_CODE1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String kyosoShubetsuCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KYOSO_SHUBETSU_CODE2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String kyosoShubetsuCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.KYOSO_JOKEN_CODE1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String kyosoJokenCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.ZENJITSU_HATSUBAI_FLAG
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String zenjitsuHatsubaiFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.ODDS_HAPPYO_JIKOKU1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Date oddsHappyoJikoku1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.ODDS_HAPPYO_JIKOKU2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Date oddsHappyoJikoku2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.TOROKU_TOSU
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Short torokuTosu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_odds_master_yoso.TORIKESHI_TOSU
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private Short torikeshiTosu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.RACE_CODE
     *
     * @return the value of jvd_odds_master_yoso.RACE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getRaceCode() {
        return raceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.RACE_CODE
     *
     * @param raceCode the value for jvd_odds_master_yoso.RACE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setRaceCode(String raceCode) {
        this.raceCode = raceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.INSERT_TIMESTAMP
     *
     * @return the value of jvd_odds_master_yoso.INSERT_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Date getInsertTimestamp() {
        return insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.INSERT_TIMESTAMP
     *
     * @param insertTimestamp the value for jvd_odds_master_yoso.INSERT_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setInsertTimestamp(Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.UPDATE_TIMESTAMP
     *
     * @return the value of jvd_odds_master_yoso.UPDATE_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for jvd_odds_master_yoso.UPDATE_TIMESTAMP
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.RECORD_SHUBETSU_ID
     *
     * @return the value of jvd_odds_master_yoso.RECORD_SHUBETSU_ID
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getRecordShubetsuId() {
        return recordShubetsuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.RECORD_SHUBETSU_ID
     *
     * @param recordShubetsuId the value for jvd_odds_master_yoso.RECORD_SHUBETSU_ID
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setRecordShubetsuId(String recordShubetsuId) {
        this.recordShubetsuId = recordShubetsuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.DATA_KUBUN
     *
     * @return the value of jvd_odds_master_yoso.DATA_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getDataKubun() {
        return dataKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.DATA_KUBUN
     *
     * @param dataKubun the value for jvd_odds_master_yoso.DATA_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setDataKubun(String dataKubun) {
        this.dataKubun = dataKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.DATA_SAKUSEI_NENGAPPI
     *
     * @return the value of jvd_odds_master_yoso.DATA_SAKUSEI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Date getDataSakuseiNengappi() {
        return dataSakuseiNengappi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.DATA_SAKUSEI_NENGAPPI
     *
     * @param dataSakuseiNengappi the value for jvd_odds_master_yoso.DATA_SAKUSEI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setDataSakuseiNengappi(Date dataSakuseiNengappi) {
        this.dataSakuseiNengappi = dataSakuseiNengappi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KAISAI_NENGAPPI
     *
     * @return the value of jvd_odds_master_yoso.KAISAI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Date getKaisaiNengappi() {
        return kaisaiNengappi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KAISAI_NENGAPPI
     *
     * @param kaisaiNengappi the value for jvd_odds_master_yoso.KAISAI_NENGAPPI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKaisaiNengappi(Date kaisaiNengappi) {
        this.kaisaiNengappi = kaisaiNengappi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KEIBAJO_CODE
     *
     * @return the value of jvd_odds_master_yoso.KEIBAJO_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getKeibajoCode() {
        return keibajoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KEIBAJO_CODE
     *
     * @param keibajoCode the value for jvd_odds_master_yoso.KEIBAJO_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKeibajoCode(String keibajoCode) {
        this.keibajoCode = keibajoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KAISAI_KAIJI
     *
     * @return the value of jvd_odds_master_yoso.KAISAI_KAIJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Short getKaisaiKaiji() {
        return kaisaiKaiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KAISAI_KAIJI
     *
     * @param kaisaiKaiji the value for jvd_odds_master_yoso.KAISAI_KAIJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKaisaiKaiji(Short kaisaiKaiji) {
        this.kaisaiKaiji = kaisaiKaiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KAISAI_NICHIJI
     *
     * @return the value of jvd_odds_master_yoso.KAISAI_NICHIJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Short getKaisaiNichiji() {
        return kaisaiNichiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KAISAI_NICHIJI
     *
     * @param kaisaiNichiji the value for jvd_odds_master_yoso.KAISAI_NICHIJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKaisaiNichiji(Short kaisaiNichiji) {
        this.kaisaiNichiji = kaisaiNichiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.RACE_BANGO
     *
     * @return the value of jvd_odds_master_yoso.RACE_BANGO
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Short getRaceBango() {
        return raceBango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.RACE_BANGO
     *
     * @param raceBango the value for jvd_odds_master_yoso.RACE_BANGO
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setRaceBango(Short raceBango) {
        this.raceBango = raceBango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.YOBI_CODE
     *
     * @return the value of jvd_odds_master_yoso.YOBI_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getYobiCode() {
        return yobiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.YOBI_CODE
     *
     * @param yobiCode the value for jvd_odds_master_yoso.YOBI_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setYobiCode(String yobiCode) {
        this.yobiCode = yobiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.CHUO_CHIHO_KUBUN
     *
     * @return the value of jvd_odds_master_yoso.CHUO_CHIHO_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getChuoChihoKubun() {
        return chuoChihoKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.CHUO_CHIHO_KUBUN
     *
     * @param chuoChihoKubun the value for jvd_odds_master_yoso.CHUO_CHIHO_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setChuoChihoKubun(String chuoChihoKubun) {
        this.chuoChihoKubun = chuoChihoKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.IPPAN_TOKUBETSU_KUBUN
     *
     * @return the value of jvd_odds_master_yoso.IPPAN_TOKUBETSU_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getIppanTokubetsuKubun() {
        return ippanTokubetsuKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.IPPAN_TOKUBETSU_KUBUN
     *
     * @param ippanTokubetsuKubun the value for jvd_odds_master_yoso.IPPAN_TOKUBETSU_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setIppanTokubetsuKubun(String ippanTokubetsuKubun) {
        this.ippanTokubetsuKubun = ippanTokubetsuKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.HEICHI_SHOGAI_KUBUN
     *
     * @return the value of jvd_odds_master_yoso.HEICHI_SHOGAI_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getHeichiShogaiKubun() {
        return heichiShogaiKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.HEICHI_SHOGAI_KUBUN
     *
     * @param heichiShogaiKubun the value for jvd_odds_master_yoso.HEICHI_SHOGAI_KUBUN
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setHeichiShogaiKubun(String heichiShogaiKubun) {
        this.heichiShogaiKubun = heichiShogaiKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.JUSHO_KAIJI
     *
     * @return the value of jvd_odds_master_yoso.JUSHO_KAIJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Short getJushoKaiji() {
        return jushoKaiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.JUSHO_KAIJI
     *
     * @param jushoKaiji the value for jvd_odds_master_yoso.JUSHO_KAIJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setJushoKaiji(Short jushoKaiji) {
        this.jushoKaiji = jushoKaiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KYOSOMEI_15MOJI
     *
     * @return the value of jvd_odds_master_yoso.KYOSOMEI_15MOJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getKyosomei15moji() {
        return kyosomei15moji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KYOSOMEI_15MOJI
     *
     * @param kyosomei15moji the value for jvd_odds_master_yoso.KYOSOMEI_15MOJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKyosomei15moji(String kyosomei15moji) {
        this.kyosomei15moji = kyosomei15moji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KYOSOMEI_7MOJI
     *
     * @return the value of jvd_odds_master_yoso.KYOSOMEI_7MOJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getKyosomei7moji() {
        return kyosomei7moji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KYOSOMEI_7MOJI
     *
     * @param kyosomei7moji the value for jvd_odds_master_yoso.KYOSOMEI_7MOJI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKyosomei7moji(String kyosomei7moji) {
        this.kyosomei7moji = kyosomei7moji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.GRADE_CODE
     *
     * @return the value of jvd_odds_master_yoso.GRADE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getGradeCode() {
        return gradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.GRADE_CODE
     *
     * @param gradeCode the value for jvd_odds_master_yoso.GRADE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setGradeCode(String gradeCode) {
        this.gradeCode = gradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.JPN_FLAG
     *
     * @return the value of jvd_odds_master_yoso.JPN_FLAG
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getJpnFlag() {
        return jpnFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.JPN_FLAG
     *
     * @param jpnFlag the value for jvd_odds_master_yoso.JPN_FLAG
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setJpnFlag(String jpnFlag) {
        this.jpnFlag = jpnFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.JURYO_SHUBETSU_CODE
     *
     * @return the value of jvd_odds_master_yoso.JURYO_SHUBETSU_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getJuryoShubetsuCode() {
        return juryoShubetsuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.JURYO_SHUBETSU_CODE
     *
     * @param juryoShubetsuCode the value for jvd_odds_master_yoso.JURYO_SHUBETSU_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setJuryoShubetsuCode(String juryoShubetsuCode) {
        this.juryoShubetsuCode = juryoShubetsuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.JURYO_SHUBETSU_SHOSAI
     *
     * @return the value of jvd_odds_master_yoso.JURYO_SHUBETSU_SHOSAI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getJuryoShubetsuShosai() {
        return juryoShubetsuShosai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.JURYO_SHUBETSU_SHOSAI
     *
     * @param juryoShubetsuShosai the value for jvd_odds_master_yoso.JURYO_SHUBETSU_SHOSAI
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setJuryoShubetsuShosai(String juryoShubetsuShosai) {
        this.juryoShubetsuShosai = juryoShubetsuShosai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KYOSO_KIGO_CODE1
     *
     * @return the value of jvd_odds_master_yoso.KYOSO_KIGO_CODE1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getKyosoKigoCode1() {
        return kyosoKigoCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KYOSO_KIGO_CODE1
     *
     * @param kyosoKigoCode1 the value for jvd_odds_master_yoso.KYOSO_KIGO_CODE1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKyosoKigoCode1(String kyosoKigoCode1) {
        this.kyosoKigoCode1 = kyosoKigoCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KYOSO_KIGO_CODE2
     *
     * @return the value of jvd_odds_master_yoso.KYOSO_KIGO_CODE2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getKyosoKigoCode2() {
        return kyosoKigoCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KYOSO_KIGO_CODE2
     *
     * @param kyosoKigoCode2 the value for jvd_odds_master_yoso.KYOSO_KIGO_CODE2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKyosoKigoCode2(String kyosoKigoCode2) {
        this.kyosoKigoCode2 = kyosoKigoCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KYOSO_SHUBETSU_CODE1
     *
     * @return the value of jvd_odds_master_yoso.KYOSO_SHUBETSU_CODE1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getKyosoShubetsuCode1() {
        return kyosoShubetsuCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KYOSO_SHUBETSU_CODE1
     *
     * @param kyosoShubetsuCode1 the value for jvd_odds_master_yoso.KYOSO_SHUBETSU_CODE1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKyosoShubetsuCode1(String kyosoShubetsuCode1) {
        this.kyosoShubetsuCode1 = kyosoShubetsuCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KYOSO_SHUBETSU_CODE2
     *
     * @return the value of jvd_odds_master_yoso.KYOSO_SHUBETSU_CODE2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getKyosoShubetsuCode2() {
        return kyosoShubetsuCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KYOSO_SHUBETSU_CODE2
     *
     * @param kyosoShubetsuCode2 the value for jvd_odds_master_yoso.KYOSO_SHUBETSU_CODE2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKyosoShubetsuCode2(String kyosoShubetsuCode2) {
        this.kyosoShubetsuCode2 = kyosoShubetsuCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.KYOSO_JOKEN_CODE1
     *
     * @return the value of jvd_odds_master_yoso.KYOSO_JOKEN_CODE1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getKyosoJokenCode1() {
        return kyosoJokenCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.KYOSO_JOKEN_CODE1
     *
     * @param kyosoJokenCode1 the value for jvd_odds_master_yoso.KYOSO_JOKEN_CODE1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setKyosoJokenCode1(String kyosoJokenCode1) {
        this.kyosoJokenCode1 = kyosoJokenCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.ZENJITSU_HATSUBAI_FLAG
     *
     * @return the value of jvd_odds_master_yoso.ZENJITSU_HATSUBAI_FLAG
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getZenjitsuHatsubaiFlag() {
        return zenjitsuHatsubaiFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.ZENJITSU_HATSUBAI_FLAG
     *
     * @param zenjitsuHatsubaiFlag the value for jvd_odds_master_yoso.ZENJITSU_HATSUBAI_FLAG
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setZenjitsuHatsubaiFlag(String zenjitsuHatsubaiFlag) {
        this.zenjitsuHatsubaiFlag = zenjitsuHatsubaiFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.ODDS_HAPPYO_JIKOKU1
     *
     * @return the value of jvd_odds_master_yoso.ODDS_HAPPYO_JIKOKU1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Date getOddsHappyoJikoku1() {
        return oddsHappyoJikoku1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.ODDS_HAPPYO_JIKOKU1
     *
     * @param oddsHappyoJikoku1 the value for jvd_odds_master_yoso.ODDS_HAPPYO_JIKOKU1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setOddsHappyoJikoku1(Date oddsHappyoJikoku1) {
        this.oddsHappyoJikoku1 = oddsHappyoJikoku1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.ODDS_HAPPYO_JIKOKU2
     *
     * @return the value of jvd_odds_master_yoso.ODDS_HAPPYO_JIKOKU2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Date getOddsHappyoJikoku2() {
        return oddsHappyoJikoku2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.ODDS_HAPPYO_JIKOKU2
     *
     * @param oddsHappyoJikoku2 the value for jvd_odds_master_yoso.ODDS_HAPPYO_JIKOKU2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setOddsHappyoJikoku2(Date oddsHappyoJikoku2) {
        this.oddsHappyoJikoku2 = oddsHappyoJikoku2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.TOROKU_TOSU
     *
     * @return the value of jvd_odds_master_yoso.TOROKU_TOSU
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Short getTorokuTosu() {
        return torokuTosu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.TOROKU_TOSU
     *
     * @param torokuTosu the value for jvd_odds_master_yoso.TOROKU_TOSU
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setTorokuTosu(Short torokuTosu) {
        this.torokuTosu = torokuTosu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_odds_master_yoso.TORIKESHI_TOSU
     *
     * @return the value of jvd_odds_master_yoso.TORIKESHI_TOSU
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public Short getTorikeshiTosu() {
        return torikeshiTosu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_odds_master_yoso.TORIKESHI_TOSU
     *
     * @param torikeshiTosu the value for jvd_odds_master_yoso.TORIKESHI_TOSU
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setTorikeshiTosu(Short torikeshiTosu) {
        this.torikeshiTosu = torikeshiTosu;
    }
}