package com.pckeiba.entity;

import com.pckeiba.entity.JvdRecordMaster;
import com.pckeiba.entity.JvdRecordMasterExample;
import com.pckeiba.entity.JvdRecordMasterKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdRecordMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdRecordMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdRecordMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdRecordMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdRecordMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdRecordMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdRecordMaster> selectByExample(JvdRecordMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdRecordMaster selectByPrimaryKey(JvdRecordMasterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdRecordMaster record, @Param("example") JvdRecordMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdRecordMaster record, @Param("example") JvdRecordMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdRecordMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_record_master
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdRecordMaster record);
}