package com.pckeiba.entity;

import com.pckeiba.entity.JvdSanrentanOdds;
import com.pckeiba.entity.JvdSanrentanOddsExample;
import com.pckeiba.entity.JvdSanrentanOddsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdSanrentanOddsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdSanrentanOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdSanrentanOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdSanrentanOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdSanrentanOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdSanrentanOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdSanrentanOdds> selectByExample(JvdSanrentanOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdSanrentanOdds selectByPrimaryKey(JvdSanrentanOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdSanrentanOdds record, @Param("example") JvdSanrentanOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdSanrentanOdds record, @Param("example") JvdSanrentanOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdSanrentanOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrentan_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdSanrentanOdds record);
}