package com.pckeiba.entity;

public class JvdSanrenpukuOddsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_sanrenpuku_odds.RACE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String raceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String sanrenpukuKumiban1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String sanrenpukuKumiban2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN3
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    private String sanrenpukuKumiban3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_sanrenpuku_odds.RACE_CODE
     *
     * @return the value of jvd_sanrenpuku_odds.RACE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getRaceCode() {
        return raceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_sanrenpuku_odds.RACE_CODE
     *
     * @param raceCode the value for jvd_sanrenpuku_odds.RACE_CODE
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setRaceCode(String raceCode) {
        this.raceCode = raceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN1
     *
     * @return the value of jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getSanrenpukuKumiban1() {
        return sanrenpukuKumiban1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN1
     *
     * @param sanrenpukuKumiban1 the value for jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN1
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setSanrenpukuKumiban1(String sanrenpukuKumiban1) {
        this.sanrenpukuKumiban1 = sanrenpukuKumiban1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN2
     *
     * @return the value of jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getSanrenpukuKumiban2() {
        return sanrenpukuKumiban2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN2
     *
     * @param sanrenpukuKumiban2 the value for jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN2
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setSanrenpukuKumiban2(String sanrenpukuKumiban2) {
        this.sanrenpukuKumiban2 = sanrenpukuKumiban2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN3
     *
     * @return the value of jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN3
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public String getSanrenpukuKumiban3() {
        return sanrenpukuKumiban3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN3
     *
     * @param sanrenpukuKumiban3 the value for jvd_sanrenpuku_odds.SANRENPUKU_KUMIBAN3
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    public void setSanrenpukuKumiban3(String sanrenpukuKumiban3) {
        this.sanrenpukuKumiban3 = sanrenpukuKumiban3;
    }
}