package com.pckeiba.entity;

import com.pckeiba.entity.JvdSeisanshaSeiseki;
import com.pckeiba.entity.JvdSeisanshaSeisekiExample;
import com.pckeiba.entity.JvdSeisanshaSeisekiKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdSeisanshaSeisekiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdSeisanshaSeisekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdSeisanshaSeisekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdSeisanshaSeisekiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdSeisanshaSeiseki record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdSeisanshaSeiseki record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdSeisanshaSeiseki> selectByExample(JvdSeisanshaSeisekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdSeisanshaSeiseki selectByPrimaryKey(JvdSeisanshaSeisekiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdSeisanshaSeiseki record, @Param("example") JvdSeisanshaSeisekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdSeisanshaSeiseki record, @Param("example") JvdSeisanshaSeisekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdSeisanshaSeiseki record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_seisansha_seiseki
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdSeisanshaSeiseki record);
}