package com.pckeiba.entity;

import com.pckeiba.entity.JvdSanrenpukuOdds;
import com.pckeiba.entity.JvdSanrenpukuOddsExample;
import com.pckeiba.entity.JvdSanrenpukuOddsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdSanrenpukuOddsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdSanrenpukuOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdSanrenpukuOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdSanrenpukuOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdSanrenpukuOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdSanrenpukuOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdSanrenpukuOdds> selectByExample(JvdSanrenpukuOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdSanrenpukuOdds selectByPrimaryKey(JvdSanrenpukuOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdSanrenpukuOdds record, @Param("example") JvdSanrenpukuOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdSanrenpukuOdds record, @Param("example") JvdSanrenpukuOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdSanrenpukuOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdSanrenpukuOdds record);
}