package com.pckeiba.entity;

import com.pckeiba.entity.JvdSanrenpukuOddsYoso;
import com.pckeiba.entity.JvdSanrenpukuOddsYosoExample;
import com.pckeiba.entity.JvdSanrenpukuOddsYosoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdSanrenpukuOddsYosoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdSanrenpukuOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdSanrenpukuOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdSanrenpukuOddsYosoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdSanrenpukuOddsYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdSanrenpukuOddsYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdSanrenpukuOddsYoso> selectByExample(JvdSanrenpukuOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdSanrenpukuOddsYoso selectByPrimaryKey(JvdSanrenpukuOddsYosoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdSanrenpukuOddsYoso record, @Param("example") JvdSanrenpukuOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdSanrenpukuOddsYoso record, @Param("example") JvdSanrenpukuOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdSanrenpukuOddsYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdSanrenpukuOddsYoso record);
}