package com.pckeiba.entity;

import com.pckeiba.entity.JvdSanrenpukuHyosu;
import com.pckeiba.entity.JvdSanrenpukuHyosuExample;
import com.pckeiba.entity.JvdSanrenpukuHyosuKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdSanrenpukuHyosuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdSanrenpukuHyosuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdSanrenpukuHyosuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdSanrenpukuHyosuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdSanrenpukuHyosu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdSanrenpukuHyosu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdSanrenpukuHyosu> selectByExample(JvdSanrenpukuHyosuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdSanrenpukuHyosu selectByPrimaryKey(JvdSanrenpukuHyosuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdSanrenpukuHyosu record, @Param("example") JvdSanrenpukuHyosuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdSanrenpukuHyosu record, @Param("example") JvdSanrenpukuHyosuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdSanrenpukuHyosu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_sanrenpuku_hyosu
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdSanrenpukuHyosu record);
}