package com.pckeiba.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JvdTorokubagotoJohoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public JvdTorokubagotoJohoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRaceCodeIsNull() {
            addCriterion("RACE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andRaceCodeIsNotNull() {
            addCriterion("RACE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andRaceCodeEqualTo(String value) {
            addCriterion("RACE_CODE =", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeNotEqualTo(String value) {
            addCriterion("RACE_CODE <>", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeGreaterThan(String value) {
            addCriterion("RACE_CODE >", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RACE_CODE >=", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeLessThan(String value) {
            addCriterion("RACE_CODE <", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeLessThanOrEqualTo(String value) {
            addCriterion("RACE_CODE <=", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeLike(String value) {
            addCriterion("RACE_CODE like", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeNotLike(String value) {
            addCriterion("RACE_CODE not like", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeIn(List<String> values) {
            addCriterion("RACE_CODE in", values, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeNotIn(List<String> values) {
            addCriterion("RACE_CODE not in", values, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeBetween(String value1, String value2) {
            addCriterion("RACE_CODE between", value1, value2, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeNotBetween(String value1, String value2) {
            addCriterion("RACE_CODE not between", value1, value2, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRembanIsNull() {
            addCriterion("REMBAN is null");
            return (Criteria) this;
        }

        public Criteria andRembanIsNotNull() {
            addCriterion("REMBAN is not null");
            return (Criteria) this;
        }

        public Criteria andRembanEqualTo(Short value) {
            addCriterion("REMBAN =", value, "remban");
            return (Criteria) this;
        }

        public Criteria andRembanNotEqualTo(Short value) {
            addCriterion("REMBAN <>", value, "remban");
            return (Criteria) this;
        }

        public Criteria andRembanGreaterThan(Short value) {
            addCriterion("REMBAN >", value, "remban");
            return (Criteria) this;
        }

        public Criteria andRembanGreaterThanOrEqualTo(Short value) {
            addCriterion("REMBAN >=", value, "remban");
            return (Criteria) this;
        }

        public Criteria andRembanLessThan(Short value) {
            addCriterion("REMBAN <", value, "remban");
            return (Criteria) this;
        }

        public Criteria andRembanLessThanOrEqualTo(Short value) {
            addCriterion("REMBAN <=", value, "remban");
            return (Criteria) this;
        }

        public Criteria andRembanIn(List<Short> values) {
            addCriterion("REMBAN in", values, "remban");
            return (Criteria) this;
        }

        public Criteria andRembanNotIn(List<Short> values) {
            addCriterion("REMBAN not in", values, "remban");
            return (Criteria) this;
        }

        public Criteria andRembanBetween(Short value1, Short value2) {
            addCriterion("REMBAN between", value1, value2, "remban");
            return (Criteria) this;
        }

        public Criteria andRembanNotBetween(Short value1, Short value2) {
            addCriterion("REMBAN not between", value1, value2, "remban");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampIsNull() {
            addCriterion("INSERT_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampIsNotNull() {
            addCriterion("INSERT_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampEqualTo(Date value) {
            addCriterion("INSERT_TIMESTAMP =", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampNotEqualTo(Date value) {
            addCriterion("INSERT_TIMESTAMP <>", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampGreaterThan(Date value) {
            addCriterion("INSERT_TIMESTAMP >", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERT_TIMESTAMP >=", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampLessThan(Date value) {
            addCriterion("INSERT_TIMESTAMP <", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampLessThanOrEqualTo(Date value) {
            addCriterion("INSERT_TIMESTAMP <=", value, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampIn(List<Date> values) {
            addCriterion("INSERT_TIMESTAMP in", values, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampNotIn(List<Date> values) {
            addCriterion("INSERT_TIMESTAMP not in", values, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampBetween(Date value1, Date value2) {
            addCriterion("INSERT_TIMESTAMP between", value1, value2, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andInsertTimestampNotBetween(Date value1, Date value2) {
            addCriterion("INSERT_TIMESTAMP not between", value1, value2, "insertTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("UPDATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("UPDATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdIsNull() {
            addCriterion("RECORD_SHUBETSU_ID is null");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdIsNotNull() {
            addCriterion("RECORD_SHUBETSU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdEqualTo(String value) {
            addCriterion("RECORD_SHUBETSU_ID =", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdNotEqualTo(String value) {
            addCriterion("RECORD_SHUBETSU_ID <>", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdGreaterThan(String value) {
            addCriterion("RECORD_SHUBETSU_ID >", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdGreaterThanOrEqualTo(String value) {
            addCriterion("RECORD_SHUBETSU_ID >=", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdLessThan(String value) {
            addCriterion("RECORD_SHUBETSU_ID <", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdLessThanOrEqualTo(String value) {
            addCriterion("RECORD_SHUBETSU_ID <=", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdLike(String value) {
            addCriterion("RECORD_SHUBETSU_ID like", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdNotLike(String value) {
            addCriterion("RECORD_SHUBETSU_ID not like", value, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdIn(List<String> values) {
            addCriterion("RECORD_SHUBETSU_ID in", values, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdNotIn(List<String> values) {
            addCriterion("RECORD_SHUBETSU_ID not in", values, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdBetween(String value1, String value2) {
            addCriterion("RECORD_SHUBETSU_ID between", value1, value2, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andRecordShubetsuIdNotBetween(String value1, String value2) {
            addCriterion("RECORD_SHUBETSU_ID not between", value1, value2, "recordShubetsuId");
            return (Criteria) this;
        }

        public Criteria andDataKubunIsNull() {
            addCriterion("DATA_KUBUN is null");
            return (Criteria) this;
        }

        public Criteria andDataKubunIsNotNull() {
            addCriterion("DATA_KUBUN is not null");
            return (Criteria) this;
        }

        public Criteria andDataKubunEqualTo(String value) {
            addCriterion("DATA_KUBUN =", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotEqualTo(String value) {
            addCriterion("DATA_KUBUN <>", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunGreaterThan(String value) {
            addCriterion("DATA_KUBUN >", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_KUBUN >=", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunLessThan(String value) {
            addCriterion("DATA_KUBUN <", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunLessThanOrEqualTo(String value) {
            addCriterion("DATA_KUBUN <=", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunLike(String value) {
            addCriterion("DATA_KUBUN like", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotLike(String value) {
            addCriterion("DATA_KUBUN not like", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunIn(List<String> values) {
            addCriterion("DATA_KUBUN in", values, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotIn(List<String> values) {
            addCriterion("DATA_KUBUN not in", values, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunBetween(String value1, String value2) {
            addCriterion("DATA_KUBUN between", value1, value2, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotBetween(String value1, String value2) {
            addCriterion("DATA_KUBUN not between", value1, value2, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiIsNull() {
            addCriterion("DATA_SAKUSEI_NENGAPPI is null");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiIsNotNull() {
            addCriterion("DATA_SAKUSEI_NENGAPPI is not null");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiEqualTo(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI =", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiNotEqualTo(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI <>", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiGreaterThan(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI >", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiGreaterThanOrEqualTo(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI >=", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiLessThan(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI <", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiLessThanOrEqualTo(Date value) {
            addCriterion("DATA_SAKUSEI_NENGAPPI <=", value, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiIn(List<Date> values) {
            addCriterion("DATA_SAKUSEI_NENGAPPI in", values, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiNotIn(List<Date> values) {
            addCriterion("DATA_SAKUSEI_NENGAPPI not in", values, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiBetween(Date value1, Date value2) {
            addCriterion("DATA_SAKUSEI_NENGAPPI between", value1, value2, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andDataSakuseiNengappiNotBetween(Date value1, Date value2) {
            addCriterion("DATA_SAKUSEI_NENGAPPI not between", value1, value2, "dataSakuseiNengappi");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoIsNull() {
            addCriterion("KETTO_TOROKU_BANGO is null");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoIsNotNull() {
            addCriterion("KETTO_TOROKU_BANGO is not null");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoEqualTo(String value) {
            addCriterion("KETTO_TOROKU_BANGO =", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoNotEqualTo(String value) {
            addCriterion("KETTO_TOROKU_BANGO <>", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoGreaterThan(String value) {
            addCriterion("KETTO_TOROKU_BANGO >", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoGreaterThanOrEqualTo(String value) {
            addCriterion("KETTO_TOROKU_BANGO >=", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoLessThan(String value) {
            addCriterion("KETTO_TOROKU_BANGO <", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoLessThanOrEqualTo(String value) {
            addCriterion("KETTO_TOROKU_BANGO <=", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoLike(String value) {
            addCriterion("KETTO_TOROKU_BANGO like", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoNotLike(String value) {
            addCriterion("KETTO_TOROKU_BANGO not like", value, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoIn(List<String> values) {
            addCriterion("KETTO_TOROKU_BANGO in", values, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoNotIn(List<String> values) {
            addCriterion("KETTO_TOROKU_BANGO not in", values, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoBetween(String value1, String value2) {
            addCriterion("KETTO_TOROKU_BANGO between", value1, value2, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andKettoTorokuBangoNotBetween(String value1, String value2) {
            addCriterion("KETTO_TOROKU_BANGO not between", value1, value2, "kettoTorokuBango");
            return (Criteria) this;
        }

        public Criteria andBameiIsNull() {
            addCriterion("BAMEI is null");
            return (Criteria) this;
        }

        public Criteria andBameiIsNotNull() {
            addCriterion("BAMEI is not null");
            return (Criteria) this;
        }

        public Criteria andBameiEqualTo(String value) {
            addCriterion("BAMEI =", value, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiNotEqualTo(String value) {
            addCriterion("BAMEI <>", value, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiGreaterThan(String value) {
            addCriterion("BAMEI >", value, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiGreaterThanOrEqualTo(String value) {
            addCriterion("BAMEI >=", value, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiLessThan(String value) {
            addCriterion("BAMEI <", value, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiLessThanOrEqualTo(String value) {
            addCriterion("BAMEI <=", value, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiLike(String value) {
            addCriterion("BAMEI like", value, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiNotLike(String value) {
            addCriterion("BAMEI not like", value, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiIn(List<String> values) {
            addCriterion("BAMEI in", values, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiNotIn(List<String> values) {
            addCriterion("BAMEI not in", values, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiBetween(String value1, String value2) {
            addCriterion("BAMEI between", value1, value2, "bamei");
            return (Criteria) this;
        }

        public Criteria andBameiNotBetween(String value1, String value2) {
            addCriterion("BAMEI not between", value1, value2, "bamei");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeIsNull() {
            addCriterion("UMAKIGO_CODE is null");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeIsNotNull() {
            addCriterion("UMAKIGO_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeEqualTo(String value) {
            addCriterion("UMAKIGO_CODE =", value, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeNotEqualTo(String value) {
            addCriterion("UMAKIGO_CODE <>", value, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeGreaterThan(String value) {
            addCriterion("UMAKIGO_CODE >", value, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeGreaterThanOrEqualTo(String value) {
            addCriterion("UMAKIGO_CODE >=", value, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeLessThan(String value) {
            addCriterion("UMAKIGO_CODE <", value, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeLessThanOrEqualTo(String value) {
            addCriterion("UMAKIGO_CODE <=", value, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeLike(String value) {
            addCriterion("UMAKIGO_CODE like", value, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeNotLike(String value) {
            addCriterion("UMAKIGO_CODE not like", value, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeIn(List<String> values) {
            addCriterion("UMAKIGO_CODE in", values, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeNotIn(List<String> values) {
            addCriterion("UMAKIGO_CODE not in", values, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeBetween(String value1, String value2) {
            addCriterion("UMAKIGO_CODE between", value1, value2, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andUmakigoCodeNotBetween(String value1, String value2) {
            addCriterion("UMAKIGO_CODE not between", value1, value2, "umakigoCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeIsNull() {
            addCriterion("SEIBETSU_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeIsNotNull() {
            addCriterion("SEIBETSU_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeEqualTo(String value) {
            addCriterion("SEIBETSU_CODE =", value, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeNotEqualTo(String value) {
            addCriterion("SEIBETSU_CODE <>", value, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeGreaterThan(String value) {
            addCriterion("SEIBETSU_CODE >", value, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SEIBETSU_CODE >=", value, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeLessThan(String value) {
            addCriterion("SEIBETSU_CODE <", value, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeLessThanOrEqualTo(String value) {
            addCriterion("SEIBETSU_CODE <=", value, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeLike(String value) {
            addCriterion("SEIBETSU_CODE like", value, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeNotLike(String value) {
            addCriterion("SEIBETSU_CODE not like", value, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeIn(List<String> values) {
            addCriterion("SEIBETSU_CODE in", values, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeNotIn(List<String> values) {
            addCriterion("SEIBETSU_CODE not in", values, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeBetween(String value1, String value2) {
            addCriterion("SEIBETSU_CODE between", value1, value2, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andSeibetsuCodeNotBetween(String value1, String value2) {
            addCriterion("SEIBETSU_CODE not between", value1, value2, "seibetsuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeIsNull() {
            addCriterion("TOZAI_SHOZOKU_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeIsNotNull() {
            addCriterion("TOZAI_SHOZOKU_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeEqualTo(String value) {
            addCriterion("TOZAI_SHOZOKU_CODE =", value, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeNotEqualTo(String value) {
            addCriterion("TOZAI_SHOZOKU_CODE <>", value, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeGreaterThan(String value) {
            addCriterion("TOZAI_SHOZOKU_CODE >", value, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TOZAI_SHOZOKU_CODE >=", value, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeLessThan(String value) {
            addCriterion("TOZAI_SHOZOKU_CODE <", value, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeLessThanOrEqualTo(String value) {
            addCriterion("TOZAI_SHOZOKU_CODE <=", value, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeLike(String value) {
            addCriterion("TOZAI_SHOZOKU_CODE like", value, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeNotLike(String value) {
            addCriterion("TOZAI_SHOZOKU_CODE not like", value, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeIn(List<String> values) {
            addCriterion("TOZAI_SHOZOKU_CODE in", values, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeNotIn(List<String> values) {
            addCriterion("TOZAI_SHOZOKU_CODE not in", values, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeBetween(String value1, String value2) {
            addCriterion("TOZAI_SHOZOKU_CODE between", value1, value2, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andTozaiShozokuCodeNotBetween(String value1, String value2) {
            addCriterion("TOZAI_SHOZOKU_CODE not between", value1, value2, "tozaiShozokuCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeIsNull() {
            addCriterion("CHOKYOSHI_CODE is null");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeIsNotNull() {
            addCriterion("CHOKYOSHI_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeEqualTo(String value) {
            addCriterion("CHOKYOSHI_CODE =", value, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeNotEqualTo(String value) {
            addCriterion("CHOKYOSHI_CODE <>", value, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeGreaterThan(String value) {
            addCriterion("CHOKYOSHI_CODE >", value, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CHOKYOSHI_CODE >=", value, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeLessThan(String value) {
            addCriterion("CHOKYOSHI_CODE <", value, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeLessThanOrEqualTo(String value) {
            addCriterion("CHOKYOSHI_CODE <=", value, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeLike(String value) {
            addCriterion("CHOKYOSHI_CODE like", value, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeNotLike(String value) {
            addCriterion("CHOKYOSHI_CODE not like", value, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeIn(List<String> values) {
            addCriterion("CHOKYOSHI_CODE in", values, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeNotIn(List<String> values) {
            addCriterion("CHOKYOSHI_CODE not in", values, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeBetween(String value1, String value2) {
            addCriterion("CHOKYOSHI_CODE between", value1, value2, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshiCodeNotBetween(String value1, String value2) {
            addCriterion("CHOKYOSHI_CODE not between", value1, value2, "chokyoshiCode");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoIsNull() {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO is null");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoIsNotNull() {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO is not null");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoEqualTo(String value) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO =", value, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoNotEqualTo(String value) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO <>", value, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoGreaterThan(String value) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO >", value, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoGreaterThanOrEqualTo(String value) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO >=", value, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoLessThan(String value) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO <", value, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoLessThanOrEqualTo(String value) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO <=", value, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoLike(String value) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO like", value, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoNotLike(String value) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO not like", value, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoIn(List<String> values) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO in", values, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoNotIn(List<String> values) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO not in", values, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoBetween(String value1, String value2) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO between", value1, value2, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andChokyoshimeiRyakushoNotBetween(String value1, String value2) {
            addCriterion("CHOKYOSHIMEI_RYAKUSHO not between", value1, value2, "chokyoshimeiRyakusho");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoIsNull() {
            addCriterion("FUTAN_JURYO is null");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoIsNotNull() {
            addCriterion("FUTAN_JURYO is not null");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoEqualTo(BigDecimal value) {
            addCriterion("FUTAN_JURYO =", value, "futanJuryo");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoNotEqualTo(BigDecimal value) {
            addCriterion("FUTAN_JURYO <>", value, "futanJuryo");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoGreaterThan(BigDecimal value) {
            addCriterion("FUTAN_JURYO >", value, "futanJuryo");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FUTAN_JURYO >=", value, "futanJuryo");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoLessThan(BigDecimal value) {
            addCriterion("FUTAN_JURYO <", value, "futanJuryo");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FUTAN_JURYO <=", value, "futanJuryo");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoIn(List<BigDecimal> values) {
            addCriterion("FUTAN_JURYO in", values, "futanJuryo");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoNotIn(List<BigDecimal> values) {
            addCriterion("FUTAN_JURYO not in", values, "futanJuryo");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUTAN_JURYO between", value1, value2, "futanJuryo");
            return (Criteria) this;
        }

        public Criteria andFutanJuryoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUTAN_JURYO not between", value1, value2, "futanJuryo");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunIsNull() {
            addCriterion("KORYU_KUBUN is null");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunIsNotNull() {
            addCriterion("KORYU_KUBUN is not null");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunEqualTo(String value) {
            addCriterion("KORYU_KUBUN =", value, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunNotEqualTo(String value) {
            addCriterion("KORYU_KUBUN <>", value, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunGreaterThan(String value) {
            addCriterion("KORYU_KUBUN >", value, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunGreaterThanOrEqualTo(String value) {
            addCriterion("KORYU_KUBUN >=", value, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunLessThan(String value) {
            addCriterion("KORYU_KUBUN <", value, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunLessThanOrEqualTo(String value) {
            addCriterion("KORYU_KUBUN <=", value, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunLike(String value) {
            addCriterion("KORYU_KUBUN like", value, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunNotLike(String value) {
            addCriterion("KORYU_KUBUN not like", value, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunIn(List<String> values) {
            addCriterion("KORYU_KUBUN in", values, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunNotIn(List<String> values) {
            addCriterion("KORYU_KUBUN not in", values, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunBetween(String value1, String value2) {
            addCriterion("KORYU_KUBUN between", value1, value2, "koryuKubun");
            return (Criteria) this;
        }

        public Criteria andKoryuKubunNotBetween(String value1, String value2) {
            addCriterion("KORYU_KUBUN not between", value1, value2, "koryuKubun");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated do_not_delete_during_merge Thu May 02 12:36:46 GMT+09:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jvd_torokubagoto_joho
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}