package com.pckeiba.entity;

import com.pckeiba.entity.JvdTanpukuOddsYoso;
import com.pckeiba.entity.JvdTanpukuOddsYosoExample;
import com.pckeiba.entity.JvdTanpukuOddsYosoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdTanpukuOddsYosoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdTanpukuOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdTanpukuOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdTanpukuOddsYosoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdTanpukuOddsYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdTanpukuOddsYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdTanpukuOddsYoso> selectByExample(JvdTanpukuOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdTanpukuOddsYoso selectByPrimaryKey(JvdTanpukuOddsYosoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdTanpukuOddsYoso record, @Param("example") JvdTanpukuOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdTanpukuOddsYoso record, @Param("example") JvdTanpukuOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdTanpukuOddsYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tanpuku_odds_yoso
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdTanpukuOddsYoso record);
}