package com.pckeiba.entity;

import com.pckeiba.entity.JvdTenkoBabaJotai;
import com.pckeiba.entity.JvdTenkoBabaJotaiExample;
import com.pckeiba.entity.JvdTenkoBabaJotaiKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdTenkoBabaJotaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdTenkoBabaJotaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdTenkoBabaJotaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdTenkoBabaJotaiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdTenkoBabaJotai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdTenkoBabaJotai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdTenkoBabaJotai> selectByExample(JvdTenkoBabaJotaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdTenkoBabaJotai selectByPrimaryKey(JvdTenkoBabaJotaiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdTenkoBabaJotai record, @Param("example") JvdTenkoBabaJotaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdTenkoBabaJotai record, @Param("example") JvdTenkoBabaJotaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdTenkoBabaJotai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_tenko_baba_jotai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdTenkoBabaJotai record);
}