package com.pckeiba.entity;

import com.pckeiba.entity.JvdTorikeshiJogai;
import com.pckeiba.entity.JvdTorikeshiJogaiExample;
import com.pckeiba.entity.JvdTorikeshiJogaiKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdTorikeshiJogaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdTorikeshiJogaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdTorikeshiJogaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdTorikeshiJogaiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdTorikeshiJogai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdTorikeshiJogai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdTorikeshiJogai> selectByExample(JvdTorikeshiJogaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdTorikeshiJogai selectByPrimaryKey(JvdTorikeshiJogaiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdTorikeshiJogai record, @Param("example") JvdTorikeshiJogaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdTorikeshiJogai record, @Param("example") JvdTorikeshiJogaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdTorikeshiJogai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_torikeshi_jogai
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdTorikeshiJogai record);
}