package com.pckeiba.entity;

import com.pckeiba.entity.JvdUmatanOdds;
import com.pckeiba.entity.JvdUmatanOddsExample;
import com.pckeiba.entity.JvdUmatanOddsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdUmatanOddsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdUmatanOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdUmatanOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdUmatanOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdUmatanOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdUmatanOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdUmatanOdds> selectByExample(JvdUmatanOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdUmatanOdds selectByPrimaryKey(JvdUmatanOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdUmatanOdds record, @Param("example") JvdUmatanOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdUmatanOdds record, @Param("example") JvdUmatanOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdUmatanOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdUmatanOdds record);
}