package com.pckeiba.entity;

import com.pckeiba.entity.JvdUmatanHyosu;
import com.pckeiba.entity.JvdUmatanHyosuExample;
import com.pckeiba.entity.JvdUmatanHyosuKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdUmatanHyosuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdUmatanHyosuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdUmatanHyosuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdUmatanHyosuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdUmatanHyosu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdUmatanHyosu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdUmatanHyosu> selectByExample(JvdUmatanHyosuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdUmatanHyosu selectByPrimaryKey(JvdUmatanHyosuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdUmatanHyosu record, @Param("example") JvdUmatanHyosuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdUmatanHyosu record, @Param("example") JvdUmatanHyosuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdUmatanHyosu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_hyosu
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdUmatanHyosu record);
}