package com.pckeiba.entity;

import com.pckeiba.entity.JvdUmatanOddsYoso;
import com.pckeiba.entity.JvdUmatanOddsYosoExample;
import com.pckeiba.entity.JvdUmatanOddsYosoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdUmatanOddsYosoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int countByExample(JvdUmatanOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByExample(JvdUmatanOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdUmatanOddsYosoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insert(JvdUmatanOddsYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int insertSelective(JvdUmatanOddsYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    List<JvdUmatanOddsYoso> selectByExample(JvdUmatanOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    JvdUmatanOddsYoso selectByPrimaryKey(JvdUmatanOddsYosoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdUmatanOddsYoso record, @Param("example") JvdUmatanOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdUmatanOddsYoso record, @Param("example") JvdUmatanOddsYosoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdUmatanOddsYoso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_umatan_odds_yoso
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdUmatanOddsYoso record);
}