package com.pckeiba.entity;

import com.pckeiba.entity.JvdWakurenOdds;
import com.pckeiba.entity.JvdWakurenOddsExample;
import com.pckeiba.entity.JvdWakurenOddsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdWakurenOddsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdWakurenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdWakurenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdWakurenOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdWakurenOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdWakurenOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdWakurenOdds> selectByExample(JvdWakurenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdWakurenOdds selectByPrimaryKey(JvdWakurenOddsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdWakurenOdds record, @Param("example") JvdWakurenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdWakurenOdds record, @Param("example") JvdWakurenOddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdWakurenOdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_wakuren_odds
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdWakurenOdds record);
}