package com.pckeiba.entity;

import com.pckeiba.entity.JvdWin5Haraimodoshi;
import com.pckeiba.entity.JvdWin5HaraimodoshiExample;
import com.pckeiba.entity.JvdWin5HaraimodoshiKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JvdWin5HaraimodoshiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int countByExample(JvdWin5HaraimodoshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByExample(JvdWin5HaraimodoshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int deleteByPrimaryKey(JvdWin5HaraimodoshiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insert(JvdWin5Haraimodoshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int insertSelective(JvdWin5Haraimodoshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    List<JvdWin5Haraimodoshi> selectByExample(JvdWin5HaraimodoshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    JvdWin5Haraimodoshi selectByPrimaryKey(JvdWin5HaraimodoshiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") JvdWin5Haraimodoshi record, @Param("example") JvdWin5HaraimodoshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByExample(@Param("record") JvdWin5Haraimodoshi record, @Param("example") JvdWin5HaraimodoshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(JvdWin5Haraimodoshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jvd_win5_haraimodoshi
     *
     * @mbggenerated Mon Apr 29 22:52:28 GMT+09:00 2019
     */
    int updateByPrimaryKey(JvdWin5Haraimodoshi record);
}