package com.pckeiba.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ViewRaceShosaiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public ViewRaceShosaiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDataKubunIsNull() {
            addCriterion("DATA_KUBUN is null");
            return (Criteria) this;
        }

        public Criteria andDataKubunIsNotNull() {
            addCriterion("DATA_KUBUN is not null");
            return (Criteria) this;
        }

        public Criteria andDataKubunEqualTo(String value) {
            addCriterion("DATA_KUBUN =", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotEqualTo(String value) {
            addCriterion("DATA_KUBUN <>", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunGreaterThan(String value) {
            addCriterion("DATA_KUBUN >", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_KUBUN >=", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunLessThan(String value) {
            addCriterion("DATA_KUBUN <", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunLessThanOrEqualTo(String value) {
            addCriterion("DATA_KUBUN <=", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunLike(String value) {
            addCriterion("DATA_KUBUN like", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotLike(String value) {
            addCriterion("DATA_KUBUN not like", value, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunIn(List<String> values) {
            addCriterion("DATA_KUBUN in", values, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotIn(List<String> values) {
            addCriterion("DATA_KUBUN not in", values, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunBetween(String value1, String value2) {
            addCriterion("DATA_KUBUN between", value1, value2, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andDataKubunNotBetween(String value1, String value2) {
            addCriterion("DATA_KUBUN not between", value1, value2, "dataKubun");
            return (Criteria) this;
        }

        public Criteria andRaceCodeIsNull() {
            addCriterion("RACE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andRaceCodeIsNotNull() {
            addCriterion("RACE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andRaceCodeEqualTo(String value) {
            addCriterion("RACE_CODE =", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeNotEqualTo(String value) {
            addCriterion("RACE_CODE <>", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeGreaterThan(String value) {
            addCriterion("RACE_CODE >", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RACE_CODE >=", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeLessThan(String value) {
            addCriterion("RACE_CODE <", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeLessThanOrEqualTo(String value) {
            addCriterion("RACE_CODE <=", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeLike(String value) {
            addCriterion("RACE_CODE like", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeNotLike(String value) {
            addCriterion("RACE_CODE not like", value, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeIn(List<String> values) {
            addCriterion("RACE_CODE in", values, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeNotIn(List<String> values) {
            addCriterion("RACE_CODE not in", values, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeBetween(String value1, String value2) {
            addCriterion("RACE_CODE between", value1, value2, "raceCode");
            return (Criteria) this;
        }

        public Criteria andRaceCodeNotBetween(String value1, String value2) {
            addCriterion("RACE_CODE not between", value1, value2, "raceCode");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiIsNull() {
            addCriterion("KAISAI_NENGAPPI is null");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiIsNotNull() {
            addCriterion("KAISAI_NENGAPPI is not null");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiEqualTo(Date value) {
            addCriterion("KAISAI_NENGAPPI =", value, "kaisaiNengappi");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiNotEqualTo(Date value) {
            addCriterion("KAISAI_NENGAPPI <>", value, "kaisaiNengappi");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiGreaterThan(Date value) {
            addCriterion("KAISAI_NENGAPPI >", value, "kaisaiNengappi");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiGreaterThanOrEqualTo(Date value) {
            addCriterion("KAISAI_NENGAPPI >=", value, "kaisaiNengappi");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiLessThan(Date value) {
            addCriterion("KAISAI_NENGAPPI <", value, "kaisaiNengappi");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiLessThanOrEqualTo(Date value) {
            addCriterion("KAISAI_NENGAPPI <=", value, "kaisaiNengappi");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiIn(List<Date> values) {
            addCriterion("KAISAI_NENGAPPI in", values, "kaisaiNengappi");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiNotIn(List<Date> values) {
            addCriterion("KAISAI_NENGAPPI not in", values, "kaisaiNengappi");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiBetween(Date value1, Date value2) {
            addCriterion("KAISAI_NENGAPPI between", value1, value2, "kaisaiNengappi");
            return (Criteria) this;
        }

        public Criteria andKaisaiNengappiNotBetween(Date value1, Date value2) {
            addCriterion("KAISAI_NENGAPPI not between", value1, value2, "kaisaiNengappi");
            return (Criteria) this;
        }

        public Criteria andKeibajoIsNull() {
            addCriterion("KEIBAJO is null");
            return (Criteria) this;
        }

        public Criteria andKeibajoIsNotNull() {
            addCriterion("KEIBAJO is not null");
            return (Criteria) this;
        }

        public Criteria andKeibajoEqualTo(String value) {
            addCriterion("KEIBAJO =", value, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoNotEqualTo(String value) {
            addCriterion("KEIBAJO <>", value, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoGreaterThan(String value) {
            addCriterion("KEIBAJO >", value, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoGreaterThanOrEqualTo(String value) {
            addCriterion("KEIBAJO >=", value, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoLessThan(String value) {
            addCriterion("KEIBAJO <", value, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoLessThanOrEqualTo(String value) {
            addCriterion("KEIBAJO <=", value, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoLike(String value) {
            addCriterion("KEIBAJO like", value, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoNotLike(String value) {
            addCriterion("KEIBAJO not like", value, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoIn(List<String> values) {
            addCriterion("KEIBAJO in", values, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoNotIn(List<String> values) {
            addCriterion("KEIBAJO not in", values, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoBetween(String value1, String value2) {
            addCriterion("KEIBAJO between", value1, value2, "keibajo");
            return (Criteria) this;
        }

        public Criteria andKeibajoNotBetween(String value1, String value2) {
            addCriterion("KEIBAJO not between", value1, value2, "keibajo");
            return (Criteria) this;
        }

        public Criteria andRaceBangoIsNull() {
            addCriterion("RACE_BANGO is null");
            return (Criteria) this;
        }

        public Criteria andRaceBangoIsNotNull() {
            addCriterion("RACE_BANGO is not null");
            return (Criteria) this;
        }

        public Criteria andRaceBangoEqualTo(Short value) {
            addCriterion("RACE_BANGO =", value, "raceBango");
            return (Criteria) this;
        }

        public Criteria andRaceBangoNotEqualTo(Short value) {
            addCriterion("RACE_BANGO <>", value, "raceBango");
            return (Criteria) this;
        }

        public Criteria andRaceBangoGreaterThan(Short value) {
            addCriterion("RACE_BANGO >", value, "raceBango");
            return (Criteria) this;
        }

        public Criteria andRaceBangoGreaterThanOrEqualTo(Short value) {
            addCriterion("RACE_BANGO >=", value, "raceBango");
            return (Criteria) this;
        }

        public Criteria andRaceBangoLessThan(Short value) {
            addCriterion("RACE_BANGO <", value, "raceBango");
            return (Criteria) this;
        }

        public Criteria andRaceBangoLessThanOrEqualTo(Short value) {
            addCriterion("RACE_BANGO <=", value, "raceBango");
            return (Criteria) this;
        }

        public Criteria andRaceBangoIn(List<Short> values) {
            addCriterion("RACE_BANGO in", values, "raceBango");
            return (Criteria) this;
        }

        public Criteria andRaceBangoNotIn(List<Short> values) {
            addCriterion("RACE_BANGO not in", values, "raceBango");
            return (Criteria) this;
        }

        public Criteria andRaceBangoBetween(Short value1, Short value2) {
            addCriterion("RACE_BANGO between", value1, value2, "raceBango");
            return (Criteria) this;
        }

        public Criteria andRaceBangoNotBetween(Short value1, Short value2) {
            addCriterion("RACE_BANGO not between", value1, value2, "raceBango");
            return (Criteria) this;
        }

        public Criteria andKaijiIsNull() {
            addCriterion("KAIJI is null");
            return (Criteria) this;
        }

        public Criteria andKaijiIsNotNull() {
            addCriterion("KAIJI is not null");
            return (Criteria) this;
        }

        public Criteria andKaijiEqualTo(Short value) {
            addCriterion("KAIJI =", value, "kaiji");
            return (Criteria) this;
        }

        public Criteria andKaijiNotEqualTo(Short value) {
            addCriterion("KAIJI <>", value, "kaiji");
            return (Criteria) this;
        }

        public Criteria andKaijiGreaterThan(Short value) {
            addCriterion("KAIJI >", value, "kaiji");
            return (Criteria) this;
        }

        public Criteria andKaijiGreaterThanOrEqualTo(Short value) {
            addCriterion("KAIJI >=", value, "kaiji");
            return (Criteria) this;
        }

        public Criteria andKaijiLessThan(Short value) {
            addCriterion("KAIJI <", value, "kaiji");
            return (Criteria) this;
        }

        public Criteria andKaijiLessThanOrEqualTo(Short value) {
            addCriterion("KAIJI <=", value, "kaiji");
            return (Criteria) this;
        }

        public Criteria andKaijiIn(List<Short> values) {
            addCriterion("KAIJI in", values, "kaiji");
            return (Criteria) this;
        }

        public Criteria andKaijiNotIn(List<Short> values) {
            addCriterion("KAIJI not in", values, "kaiji");
            return (Criteria) this;
        }

        public Criteria andKaijiBetween(Short value1, Short value2) {
            addCriterion("KAIJI between", value1, value2, "kaiji");
            return (Criteria) this;
        }

        public Criteria andKaijiNotBetween(Short value1, Short value2) {
            addCriterion("KAIJI not between", value1, value2, "kaiji");
            return (Criteria) this;
        }

        public Criteria andNichijiIsNull() {
            addCriterion("NICHIJI is null");
            return (Criteria) this;
        }

        public Criteria andNichijiIsNotNull() {
            addCriterion("NICHIJI is not null");
            return (Criteria) this;
        }

        public Criteria andNichijiEqualTo(Short value) {
            addCriterion("NICHIJI =", value, "nichiji");
            return (Criteria) this;
        }

        public Criteria andNichijiNotEqualTo(Short value) {
            addCriterion("NICHIJI <>", value, "nichiji");
            return (Criteria) this;
        }

        public Criteria andNichijiGreaterThan(Short value) {
            addCriterion("NICHIJI >", value, "nichiji");
            return (Criteria) this;
        }

        public Criteria andNichijiGreaterThanOrEqualTo(Short value) {
            addCriterion("NICHIJI >=", value, "nichiji");
            return (Criteria) this;
        }

        public Criteria andNichijiLessThan(Short value) {
            addCriterion("NICHIJI <", value, "nichiji");
            return (Criteria) this;
        }

        public Criteria andNichijiLessThanOrEqualTo(Short value) {
            addCriterion("NICHIJI <=", value, "nichiji");
            return (Criteria) this;
        }

        public Criteria andNichijiIn(List<Short> values) {
            addCriterion("NICHIJI in", values, "nichiji");
            return (Criteria) this;
        }

        public Criteria andNichijiNotIn(List<Short> values) {
            addCriterion("NICHIJI not in", values, "nichiji");
            return (Criteria) this;
        }

        public Criteria andNichijiBetween(Short value1, Short value2) {
            addCriterion("NICHIJI between", value1, value2, "nichiji");
            return (Criteria) this;
        }

        public Criteria andNichijiNotBetween(Short value1, Short value2) {
            addCriterion("NICHIJI not between", value1, value2, "nichiji");
            return (Criteria) this;
        }

        public Criteria andRIsNull() {
            addCriterion("R is null");
            return (Criteria) this;
        }

        public Criteria andRIsNotNull() {
            addCriterion("R is not null");
            return (Criteria) this;
        }

        public Criteria andREqualTo(Short value) {
            addCriterion("R =", value, "r");
            return (Criteria) this;
        }

        public Criteria andRNotEqualTo(Short value) {
            addCriterion("R <>", value, "r");
            return (Criteria) this;
        }

        public Criteria andRGreaterThan(Short value) {
            addCriterion("R >", value, "r");
            return (Criteria) this;
        }

        public Criteria andRGreaterThanOrEqualTo(Short value) {
            addCriterion("R >=", value, "r");
            return (Criteria) this;
        }

        public Criteria andRLessThan(Short value) {
            addCriterion("R <", value, "r");
            return (Criteria) this;
        }

        public Criteria andRLessThanOrEqualTo(Short value) {
            addCriterion("R <=", value, "r");
            return (Criteria) this;
        }

        public Criteria andRIn(List<Short> values) {
            addCriterion("R in", values, "r");
            return (Criteria) this;
        }

        public Criteria andRNotIn(List<Short> values) {
            addCriterion("R not in", values, "r");
            return (Criteria) this;
        }

        public Criteria andRBetween(Short value1, Short value2) {
            addCriterion("R between", value1, value2, "r");
            return (Criteria) this;
        }

        public Criteria andRNotBetween(Short value1, Short value2) {
            addCriterion("R not between", value1, value2, "r");
            return (Criteria) this;
        }

        public Criteria andBabaIsNull() {
            addCriterion("BABA is null");
            return (Criteria) this;
        }

        public Criteria andBabaIsNotNull() {
            addCriterion("BABA is not null");
            return (Criteria) this;
        }

        public Criteria andBabaEqualTo(Integer value) {
            addCriterion("BABA =", value, "baba");
            return (Criteria) this;
        }

        public Criteria andBabaNotEqualTo(Integer value) {
            addCriterion("BABA <>", value, "baba");
            return (Criteria) this;
        }

        public Criteria andBabaGreaterThan(Integer value) {
            addCriterion("BABA >", value, "baba");
            return (Criteria) this;
        }

        public Criteria andBabaGreaterThanOrEqualTo(Integer value) {
            addCriterion("BABA >=", value, "baba");
            return (Criteria) this;
        }

        public Criteria andBabaLessThan(Integer value) {
            addCriterion("BABA <", value, "baba");
            return (Criteria) this;
        }

        public Criteria andBabaLessThanOrEqualTo(Integer value) {
            addCriterion("BABA <=", value, "baba");
            return (Criteria) this;
        }

        public Criteria andBabaIn(List<Integer> values) {
            addCriterion("BABA in", values, "baba");
            return (Criteria) this;
        }

        public Criteria andBabaNotIn(List<Integer> values) {
            addCriterion("BABA not in", values, "baba");
            return (Criteria) this;
        }

        public Criteria andBabaBetween(Integer value1, Integer value2) {
            addCriterion("BABA between", value1, value2, "baba");
            return (Criteria) this;
        }

        public Criteria andBabaNotBetween(Integer value1, Integer value2) {
            addCriterion("BABA not between", value1, value2, "baba");
            return (Criteria) this;
        }

        public Criteria andYobiIsNull() {
            addCriterion("YOBI is null");
            return (Criteria) this;
        }

        public Criteria andYobiIsNotNull() {
            addCriterion("YOBI is not null");
            return (Criteria) this;
        }

        public Criteria andYobiEqualTo(String value) {
            addCriterion("YOBI =", value, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiNotEqualTo(String value) {
            addCriterion("YOBI <>", value, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiGreaterThan(String value) {
            addCriterion("YOBI >", value, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiGreaterThanOrEqualTo(String value) {
            addCriterion("YOBI >=", value, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiLessThan(String value) {
            addCriterion("YOBI <", value, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiLessThanOrEqualTo(String value) {
            addCriterion("YOBI <=", value, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiLike(String value) {
            addCriterion("YOBI like", value, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiNotLike(String value) {
            addCriterion("YOBI not like", value, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiIn(List<String> values) {
            addCriterion("YOBI in", values, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiNotIn(List<String> values) {
            addCriterion("YOBI not in", values, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiBetween(String value1, String value2) {
            addCriterion("YOBI between", value1, value2, "yobi");
            return (Criteria) this;
        }

        public Criteria andYobiNotBetween(String value1, String value2) {
            addCriterion("YOBI not between", value1, value2, "yobi");
            return (Criteria) this;
        }

        public Criteria andShibaIsNull() {
            addCriterion("SHIBA is null");
            return (Criteria) this;
        }

        public Criteria andShibaIsNotNull() {
            addCriterion("SHIBA is not null");
            return (Criteria) this;
        }

        public Criteria andShibaEqualTo(String value) {
            addCriterion("SHIBA =", value, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaNotEqualTo(String value) {
            addCriterion("SHIBA <>", value, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaGreaterThan(String value) {
            addCriterion("SHIBA >", value, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaGreaterThanOrEqualTo(String value) {
            addCriterion("SHIBA >=", value, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaLessThan(String value) {
            addCriterion("SHIBA <", value, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaLessThanOrEqualTo(String value) {
            addCriterion("SHIBA <=", value, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaLike(String value) {
            addCriterion("SHIBA like", value, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaNotLike(String value) {
            addCriterion("SHIBA not like", value, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaIn(List<String> values) {
            addCriterion("SHIBA in", values, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaNotIn(List<String> values) {
            addCriterion("SHIBA not in", values, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaBetween(String value1, String value2) {
            addCriterion("SHIBA between", value1, value2, "shiba");
            return (Criteria) this;
        }

        public Criteria andShibaNotBetween(String value1, String value2) {
            addCriterion("SHIBA not between", value1, value2, "shiba");
            return (Criteria) this;
        }

        public Criteria andDirtIsNull() {
            addCriterion("DIRT is null");
            return (Criteria) this;
        }

        public Criteria andDirtIsNotNull() {
            addCriterion("DIRT is not null");
            return (Criteria) this;
        }

        public Criteria andDirtEqualTo(String value) {
            addCriterion("DIRT =", value, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtNotEqualTo(String value) {
            addCriterion("DIRT <>", value, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtGreaterThan(String value) {
            addCriterion("DIRT >", value, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtGreaterThanOrEqualTo(String value) {
            addCriterion("DIRT >=", value, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtLessThan(String value) {
            addCriterion("DIRT <", value, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtLessThanOrEqualTo(String value) {
            addCriterion("DIRT <=", value, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtLike(String value) {
            addCriterion("DIRT like", value, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtNotLike(String value) {
            addCriterion("DIRT not like", value, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtIn(List<String> values) {
            addCriterion("DIRT in", values, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtNotIn(List<String> values) {
            addCriterion("DIRT not in", values, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtBetween(String value1, String value2) {
            addCriterion("DIRT between", value1, value2, "dirt");
            return (Criteria) this;
        }

        public Criteria andDirtNotBetween(String value1, String value2) {
            addCriterion("DIRT not between", value1, value2, "dirt");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiIsNull() {
            addCriterion("KYOSOMEI_HONDAI is null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiIsNotNull() {
            addCriterion("KYOSOMEI_HONDAI is not null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiEqualTo(String value) {
            addCriterion("KYOSOMEI_HONDAI =", value, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiNotEqualTo(String value) {
            addCriterion("KYOSOMEI_HONDAI <>", value, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiGreaterThan(String value) {
            addCriterion("KYOSOMEI_HONDAI >", value, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiGreaterThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_HONDAI >=", value, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiLessThan(String value) {
            addCriterion("KYOSOMEI_HONDAI <", value, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiLessThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_HONDAI <=", value, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiLike(String value) {
            addCriterion("KYOSOMEI_HONDAI like", value, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiNotLike(String value) {
            addCriterion("KYOSOMEI_HONDAI not like", value, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiIn(List<String> values) {
            addCriterion("KYOSOMEI_HONDAI in", values, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiNotIn(List<String> values) {
            addCriterion("KYOSOMEI_HONDAI not in", values, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_HONDAI between", value1, value2, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiHondaiNotBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_HONDAI not between", value1, value2, "kyosomeiHondai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiIsNull() {
            addCriterion("KYOSOMEI_FUKUDAI is null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiIsNotNull() {
            addCriterion("KYOSOMEI_FUKUDAI is not null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiEqualTo(String value) {
            addCriterion("KYOSOMEI_FUKUDAI =", value, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiNotEqualTo(String value) {
            addCriterion("KYOSOMEI_FUKUDAI <>", value, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiGreaterThan(String value) {
            addCriterion("KYOSOMEI_FUKUDAI >", value, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiGreaterThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_FUKUDAI >=", value, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiLessThan(String value) {
            addCriterion("KYOSOMEI_FUKUDAI <", value, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiLessThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_FUKUDAI <=", value, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiLike(String value) {
            addCriterion("KYOSOMEI_FUKUDAI like", value, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiNotLike(String value) {
            addCriterion("KYOSOMEI_FUKUDAI not like", value, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiIn(List<String> values) {
            addCriterion("KYOSOMEI_FUKUDAI in", values, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiNotIn(List<String> values) {
            addCriterion("KYOSOMEI_FUKUDAI not in", values, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_FUKUDAI between", value1, value2, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiFukudaiNotBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_FUKUDAI not between", value1, value2, "kyosomeiFukudai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiIsNull() {
            addCriterion("KYOSOMEI_KAKKONAI is null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiIsNotNull() {
            addCriterion("KYOSOMEI_KAKKONAI is not null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiEqualTo(String value) {
            addCriterion("KYOSOMEI_KAKKONAI =", value, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiNotEqualTo(String value) {
            addCriterion("KYOSOMEI_KAKKONAI <>", value, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiGreaterThan(String value) {
            addCriterion("KYOSOMEI_KAKKONAI >", value, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiGreaterThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_KAKKONAI >=", value, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiLessThan(String value) {
            addCriterion("KYOSOMEI_KAKKONAI <", value, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiLessThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_KAKKONAI <=", value, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiLike(String value) {
            addCriterion("KYOSOMEI_KAKKONAI like", value, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiNotLike(String value) {
            addCriterion("KYOSOMEI_KAKKONAI not like", value, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiIn(List<String> values) {
            addCriterion("KYOSOMEI_KAKKONAI in", values, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiNotIn(List<String> values) {
            addCriterion("KYOSOMEI_KAKKONAI not in", values, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_KAKKONAI between", value1, value2, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKakkonaiNotBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_KAKKONAI not between", value1, value2, "kyosomeiKakkonai");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10IsNull() {
            addCriterion("KYOSOMEI_RYAKUSHO_10 is null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10IsNotNull() {
            addCriterion("KYOSOMEI_RYAKUSHO_10 is not null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10EqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 =", value, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10NotEqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 <>", value, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10GreaterThan(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 >", value, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10GreaterThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 >=", value, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10LessThan(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 <", value, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10LessThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 <=", value, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10Like(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 like", value, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10NotLike(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 not like", value, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10In(List<String> values) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 in", values, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10NotIn(List<String> values) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 not in", values, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10Between(String value1, String value2) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 between", value1, value2, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho10NotBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_RYAKUSHO_10 not between", value1, value2, "kyosomeiRyakusho10");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6IsNull() {
            addCriterion("KYOSOMEI_RYAKUSHO_6 is null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6IsNotNull() {
            addCriterion("KYOSOMEI_RYAKUSHO_6 is not null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6EqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 =", value, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6NotEqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 <>", value, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6GreaterThan(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 >", value, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6GreaterThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 >=", value, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6LessThan(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 <", value, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6LessThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 <=", value, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6Like(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 like", value, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6NotLike(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 not like", value, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6In(List<String> values) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 in", values, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6NotIn(List<String> values) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 not in", values, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6Between(String value1, String value2) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 between", value1, value2, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho6NotBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_RYAKUSHO_6 not between", value1, value2, "kyosomeiRyakusho6");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3IsNull() {
            addCriterion("KYOSOMEI_RYAKUSHO_3 is null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3IsNotNull() {
            addCriterion("KYOSOMEI_RYAKUSHO_3 is not null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3EqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 =", value, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3NotEqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 <>", value, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3GreaterThan(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 >", value, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3GreaterThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 >=", value, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3LessThan(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 <", value, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3LessThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 <=", value, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3Like(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 like", value, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3NotLike(String value) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 not like", value, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3In(List<String> values) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 in", values, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3NotIn(List<String> values) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 not in", values, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3Between(String value1, String value2) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 between", value1, value2, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiRyakusho3NotBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_RYAKUSHO_3 not between", value1, value2, "kyosomeiRyakusho3");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunIsNull() {
            addCriterion("KYOSOMEI_KUBUN is null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunIsNotNull() {
            addCriterion("KYOSOMEI_KUBUN is not null");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunEqualTo(String value) {
            addCriterion("KYOSOMEI_KUBUN =", value, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunNotEqualTo(String value) {
            addCriterion("KYOSOMEI_KUBUN <>", value, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunGreaterThan(String value) {
            addCriterion("KYOSOMEI_KUBUN >", value, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunGreaterThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_KUBUN >=", value, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunLessThan(String value) {
            addCriterion("KYOSOMEI_KUBUN <", value, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunLessThanOrEqualTo(String value) {
            addCriterion("KYOSOMEI_KUBUN <=", value, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunLike(String value) {
            addCriterion("KYOSOMEI_KUBUN like", value, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunNotLike(String value) {
            addCriterion("KYOSOMEI_KUBUN not like", value, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunIn(List<String> values) {
            addCriterion("KYOSOMEI_KUBUN in", values, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunNotIn(List<String> values) {
            addCriterion("KYOSOMEI_KUBUN not in", values, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_KUBUN between", value1, value2, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andKyosomeiKubunNotBetween(String value1, String value2) {
            addCriterion("KYOSOMEI_KUBUN not between", value1, value2, "kyosomeiKubun");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiIsNull() {
            addCriterion("JUSHO_KAIJI is null");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiIsNotNull() {
            addCriterion("JUSHO_KAIJI is not null");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiEqualTo(Short value) {
            addCriterion("JUSHO_KAIJI =", value, "jushoKaiji");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiNotEqualTo(Short value) {
            addCriterion("JUSHO_KAIJI <>", value, "jushoKaiji");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiGreaterThan(Short value) {
            addCriterion("JUSHO_KAIJI >", value, "jushoKaiji");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiGreaterThanOrEqualTo(Short value) {
            addCriterion("JUSHO_KAIJI >=", value, "jushoKaiji");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiLessThan(Short value) {
            addCriterion("JUSHO_KAIJI <", value, "jushoKaiji");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiLessThanOrEqualTo(Short value) {
            addCriterion("JUSHO_KAIJI <=", value, "jushoKaiji");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiIn(List<Short> values) {
            addCriterion("JUSHO_KAIJI in", values, "jushoKaiji");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiNotIn(List<Short> values) {
            addCriterion("JUSHO_KAIJI not in", values, "jushoKaiji");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiBetween(Short value1, Short value2) {
            addCriterion("JUSHO_KAIJI between", value1, value2, "jushoKaiji");
            return (Criteria) this;
        }

        public Criteria andJushoKaijiNotBetween(Short value1, Short value2) {
            addCriterion("JUSHO_KAIJI not between", value1, value2, "jushoKaiji");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("GRADE is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(String value) {
            addCriterion("GRADE =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(String value) {
            addCriterion("GRADE <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(String value) {
            addCriterion("GRADE >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(String value) {
            addCriterion("GRADE >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(String value) {
            addCriterion("GRADE <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(String value) {
            addCriterion("GRADE <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLike(String value) {
            addCriterion("GRADE like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotLike(String value) {
            addCriterion("GRADE not like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<String> values) {
            addCriterion("GRADE in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<String> values) {
            addCriterion("GRADE not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(String value1, String value2) {
            addCriterion("GRADE between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(String value1, String value2) {
            addCriterion("GRADE not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuIsNull() {
            addCriterion("KYOSO_SHUBETSU is null");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuIsNotNull() {
            addCriterion("KYOSO_SHUBETSU is not null");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuEqualTo(String value) {
            addCriterion("KYOSO_SHUBETSU =", value, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuNotEqualTo(String value) {
            addCriterion("KYOSO_SHUBETSU <>", value, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuGreaterThan(String value) {
            addCriterion("KYOSO_SHUBETSU >", value, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuGreaterThanOrEqualTo(String value) {
            addCriterion("KYOSO_SHUBETSU >=", value, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuLessThan(String value) {
            addCriterion("KYOSO_SHUBETSU <", value, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuLessThanOrEqualTo(String value) {
            addCriterion("KYOSO_SHUBETSU <=", value, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuLike(String value) {
            addCriterion("KYOSO_SHUBETSU like", value, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuNotLike(String value) {
            addCriterion("KYOSO_SHUBETSU not like", value, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuIn(List<String> values) {
            addCriterion("KYOSO_SHUBETSU in", values, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuNotIn(List<String> values) {
            addCriterion("KYOSO_SHUBETSU not in", values, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuBetween(String value1, String value2) {
            addCriterion("KYOSO_SHUBETSU between", value1, value2, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoShubetsuNotBetween(String value1, String value2) {
            addCriterion("KYOSO_SHUBETSU not between", value1, value2, "kyosoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeIsNull() {
            addCriterion("KYOSO_KIGO_CODE is null");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeIsNotNull() {
            addCriterion("KYOSO_KIGO_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeEqualTo(String value) {
            addCriterion("KYOSO_KIGO_CODE =", value, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeNotEqualTo(String value) {
            addCriterion("KYOSO_KIGO_CODE <>", value, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeGreaterThan(String value) {
            addCriterion("KYOSO_KIGO_CODE >", value, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeGreaterThanOrEqualTo(String value) {
            addCriterion("KYOSO_KIGO_CODE >=", value, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeLessThan(String value) {
            addCriterion("KYOSO_KIGO_CODE <", value, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeLessThanOrEqualTo(String value) {
            addCriterion("KYOSO_KIGO_CODE <=", value, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeLike(String value) {
            addCriterion("KYOSO_KIGO_CODE like", value, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeNotLike(String value) {
            addCriterion("KYOSO_KIGO_CODE not like", value, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeIn(List<String> values) {
            addCriterion("KYOSO_KIGO_CODE in", values, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeNotIn(List<String> values) {
            addCriterion("KYOSO_KIGO_CODE not in", values, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeBetween(String value1, String value2) {
            addCriterion("KYOSO_KIGO_CODE between", value1, value2, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andKyosoKigoCodeNotBetween(String value1, String value2) {
            addCriterion("KYOSO_KIGO_CODE not between", value1, value2, "kyosoKigoCode");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuIsNull() {
            addCriterion("JURYO_SHUBETSU is null");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuIsNotNull() {
            addCriterion("JURYO_SHUBETSU is not null");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuEqualTo(String value) {
            addCriterion("JURYO_SHUBETSU =", value, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuNotEqualTo(String value) {
            addCriterion("JURYO_SHUBETSU <>", value, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuGreaterThan(String value) {
            addCriterion("JURYO_SHUBETSU >", value, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuGreaterThanOrEqualTo(String value) {
            addCriterion("JURYO_SHUBETSU >=", value, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuLessThan(String value) {
            addCriterion("JURYO_SHUBETSU <", value, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuLessThanOrEqualTo(String value) {
            addCriterion("JURYO_SHUBETSU <=", value, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuLike(String value) {
            addCriterion("JURYO_SHUBETSU like", value, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuNotLike(String value) {
            addCriterion("JURYO_SHUBETSU not like", value, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuIn(List<String> values) {
            addCriterion("JURYO_SHUBETSU in", values, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuNotIn(List<String> values) {
            addCriterion("JURYO_SHUBETSU not in", values, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuBetween(String value1, String value2) {
            addCriterion("JURYO_SHUBETSU between", value1, value2, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andJuryoShubetsuNotBetween(String value1, String value2) {
            addCriterion("JURYO_SHUBETSU not between", value1, value2, "juryoShubetsu");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenIsNull() {
            addCriterion("KYOSO_JOKEN is null");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenIsNotNull() {
            addCriterion("KYOSO_JOKEN is not null");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenEqualTo(String value) {
            addCriterion("KYOSO_JOKEN =", value, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenNotEqualTo(String value) {
            addCriterion("KYOSO_JOKEN <>", value, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenGreaterThan(String value) {
            addCriterion("KYOSO_JOKEN >", value, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenGreaterThanOrEqualTo(String value) {
            addCriterion("KYOSO_JOKEN >=", value, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenLessThan(String value) {
            addCriterion("KYOSO_JOKEN <", value, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenLessThanOrEqualTo(String value) {
            addCriterion("KYOSO_JOKEN <=", value, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenLike(String value) {
            addCriterion("KYOSO_JOKEN like", value, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenNotLike(String value) {
            addCriterion("KYOSO_JOKEN not like", value, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenIn(List<String> values) {
            addCriterion("KYOSO_JOKEN in", values, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenNotIn(List<String> values) {
            addCriterion("KYOSO_JOKEN not in", values, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenBetween(String value1, String value2) {
            addCriterion("KYOSO_JOKEN between", value1, value2, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyosoJokenNotBetween(String value1, String value2) {
            addCriterion("KYOSO_JOKEN not between", value1, value2, "kyosoJoken");
            return (Criteria) this;
        }

        public Criteria andKyoriIsNull() {
            addCriterion("KYORI is null");
            return (Criteria) this;
        }

        public Criteria andKyoriIsNotNull() {
            addCriterion("KYORI is not null");
            return (Criteria) this;
        }

        public Criteria andKyoriEqualTo(Short value) {
            addCriterion("KYORI =", value, "kyori");
            return (Criteria) this;
        }

        public Criteria andKyoriNotEqualTo(Short value) {
            addCriterion("KYORI <>", value, "kyori");
            return (Criteria) this;
        }

        public Criteria andKyoriGreaterThan(Short value) {
            addCriterion("KYORI >", value, "kyori");
            return (Criteria) this;
        }

        public Criteria andKyoriGreaterThanOrEqualTo(Short value) {
            addCriterion("KYORI >=", value, "kyori");
            return (Criteria) this;
        }

        public Criteria andKyoriLessThan(Short value) {
            addCriterion("KYORI <", value, "kyori");
            return (Criteria) this;
        }

        public Criteria andKyoriLessThanOrEqualTo(Short value) {
            addCriterion("KYORI <=", value, "kyori");
            return (Criteria) this;
        }

        public Criteria andKyoriIn(List<Short> values) {
            addCriterion("KYORI in", values, "kyori");
            return (Criteria) this;
        }

        public Criteria andKyoriNotIn(List<Short> values) {
            addCriterion("KYORI not in", values, "kyori");
            return (Criteria) this;
        }

        public Criteria andKyoriBetween(Short value1, Short value2) {
            addCriterion("KYORI between", value1, value2, "kyori");
            return (Criteria) this;
        }

        public Criteria andKyoriNotBetween(Short value1, Short value2) {
            addCriterion("KYORI not between", value1, value2, "kyori");
            return (Criteria) this;
        }

        public Criteria andTrackIsNull() {
            addCriterion("TRACK is null");
            return (Criteria) this;
        }

        public Criteria andTrackIsNotNull() {
            addCriterion("TRACK is not null");
            return (Criteria) this;
        }

        public Criteria andTrackEqualTo(String value) {
            addCriterion("TRACK =", value, "track");
            return (Criteria) this;
        }

        public Criteria andTrackNotEqualTo(String value) {
            addCriterion("TRACK <>", value, "track");
            return (Criteria) this;
        }

        public Criteria andTrackGreaterThan(String value) {
            addCriterion("TRACK >", value, "track");
            return (Criteria) this;
        }

        public Criteria andTrackGreaterThanOrEqualTo(String value) {
            addCriterion("TRACK >=", value, "track");
            return (Criteria) this;
        }

        public Criteria andTrackLessThan(String value) {
            addCriterion("TRACK <", value, "track");
            return (Criteria) this;
        }

        public Criteria andTrackLessThanOrEqualTo(String value) {
            addCriterion("TRACK <=", value, "track");
            return (Criteria) this;
        }

        public Criteria andTrackLike(String value) {
            addCriterion("TRACK like", value, "track");
            return (Criteria) this;
        }

        public Criteria andTrackNotLike(String value) {
            addCriterion("TRACK not like", value, "track");
            return (Criteria) this;
        }

        public Criteria andTrackIn(List<String> values) {
            addCriterion("TRACK in", values, "track");
            return (Criteria) this;
        }

        public Criteria andTrackNotIn(List<String> values) {
            addCriterion("TRACK not in", values, "track");
            return (Criteria) this;
        }

        public Criteria andTrackBetween(String value1, String value2) {
            addCriterion("TRACK between", value1, value2, "track");
            return (Criteria) this;
        }

        public Criteria andTrackNotBetween(String value1, String value2) {
            addCriterion("TRACK not between", value1, value2, "track");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuIsNull() {
            addCriterion("HASSO_JIKOKU is null");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuIsNotNull() {
            addCriterion("HASSO_JIKOKU is not null");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuEqualTo(Date value) {
            addCriterion("HASSO_JIKOKU =", value, "hassoJikoku");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuNotEqualTo(Date value) {
            addCriterion("HASSO_JIKOKU <>", value, "hassoJikoku");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuGreaterThan(Date value) {
            addCriterion("HASSO_JIKOKU >", value, "hassoJikoku");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuGreaterThanOrEqualTo(Date value) {
            addCriterion("HASSO_JIKOKU >=", value, "hassoJikoku");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuLessThan(Date value) {
            addCriterion("HASSO_JIKOKU <", value, "hassoJikoku");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuLessThanOrEqualTo(Date value) {
            addCriterion("HASSO_JIKOKU <=", value, "hassoJikoku");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuIn(List<Date> values) {
            addCriterion("HASSO_JIKOKU in", values, "hassoJikoku");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuNotIn(List<Date> values) {
            addCriterion("HASSO_JIKOKU not in", values, "hassoJikoku");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuBetween(Date value1, Date value2) {
            addCriterion("HASSO_JIKOKU between", value1, value2, "hassoJikoku");
            return (Criteria) this;
        }

        public Criteria andHassoJikokuNotBetween(Date value1, Date value2) {
            addCriterion("HASSO_JIKOKU not between", value1, value2, "hassoJikoku");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuIsNull() {
            addCriterion("TOROKU_TOSU is null");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuIsNotNull() {
            addCriterion("TOROKU_TOSU is not null");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuEqualTo(Short value) {
            addCriterion("TOROKU_TOSU =", value, "torokuTosu");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuNotEqualTo(Short value) {
            addCriterion("TOROKU_TOSU <>", value, "torokuTosu");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuGreaterThan(Short value) {
            addCriterion("TOROKU_TOSU >", value, "torokuTosu");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuGreaterThanOrEqualTo(Short value) {
            addCriterion("TOROKU_TOSU >=", value, "torokuTosu");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuLessThan(Short value) {
            addCriterion("TOROKU_TOSU <", value, "torokuTosu");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuLessThanOrEqualTo(Short value) {
            addCriterion("TOROKU_TOSU <=", value, "torokuTosu");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuIn(List<Short> values) {
            addCriterion("TOROKU_TOSU in", values, "torokuTosu");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuNotIn(List<Short> values) {
            addCriterion("TOROKU_TOSU not in", values, "torokuTosu");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuBetween(Short value1, Short value2) {
            addCriterion("TOROKU_TOSU between", value1, value2, "torokuTosu");
            return (Criteria) this;
        }

        public Criteria andTorokuTosuNotBetween(Short value1, Short value2) {
            addCriterion("TOROKU_TOSU not between", value1, value2, "torokuTosu");
            return (Criteria) this;
        }

        public Criteria andShussoTosuIsNull() {
            addCriterion("SHUSSO_TOSU is null");
            return (Criteria) this;
        }

        public Criteria andShussoTosuIsNotNull() {
            addCriterion("SHUSSO_TOSU is not null");
            return (Criteria) this;
        }

        public Criteria andShussoTosuEqualTo(Short value) {
            addCriterion("SHUSSO_TOSU =", value, "shussoTosu");
            return (Criteria) this;
        }

        public Criteria andShussoTosuNotEqualTo(Short value) {
            addCriterion("SHUSSO_TOSU <>", value, "shussoTosu");
            return (Criteria) this;
        }

        public Criteria andShussoTosuGreaterThan(Short value) {
            addCriterion("SHUSSO_TOSU >", value, "shussoTosu");
            return (Criteria) this;
        }

        public Criteria andShussoTosuGreaterThanOrEqualTo(Short value) {
            addCriterion("SHUSSO_TOSU >=", value, "shussoTosu");
            return (Criteria) this;
        }

        public Criteria andShussoTosuLessThan(Short value) {
            addCriterion("SHUSSO_TOSU <", value, "shussoTosu");
            return (Criteria) this;
        }

        public Criteria andShussoTosuLessThanOrEqualTo(Short value) {
            addCriterion("SHUSSO_TOSU <=", value, "shussoTosu");
            return (Criteria) this;
        }

        public Criteria andShussoTosuIn(List<Short> values) {
            addCriterion("SHUSSO_TOSU in", values, "shussoTosu");
            return (Criteria) this;
        }

        public Criteria andShussoTosuNotIn(List<Short> values) {
            addCriterion("SHUSSO_TOSU not in", values, "shussoTosu");
            return (Criteria) this;
        }

        public Criteria andShussoTosuBetween(Short value1, Short value2) {
            addCriterion("SHUSSO_TOSU between", value1, value2, "shussoTosu");
            return (Criteria) this;
        }

        public Criteria andShussoTosuNotBetween(Short value1, Short value2) {
            addCriterion("SHUSSO_TOSU not between", value1, value2, "shussoTosu");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuIsNull() {
            addCriterion("NYUSEN_TOSU is null");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuIsNotNull() {
            addCriterion("NYUSEN_TOSU is not null");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuEqualTo(Short value) {
            addCriterion("NYUSEN_TOSU =", value, "nyusenTosu");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuNotEqualTo(Short value) {
            addCriterion("NYUSEN_TOSU <>", value, "nyusenTosu");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuGreaterThan(Short value) {
            addCriterion("NYUSEN_TOSU >", value, "nyusenTosu");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuGreaterThanOrEqualTo(Short value) {
            addCriterion("NYUSEN_TOSU >=", value, "nyusenTosu");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuLessThan(Short value) {
            addCriterion("NYUSEN_TOSU <", value, "nyusenTosu");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuLessThanOrEqualTo(Short value) {
            addCriterion("NYUSEN_TOSU <=", value, "nyusenTosu");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuIn(List<Short> values) {
            addCriterion("NYUSEN_TOSU in", values, "nyusenTosu");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuNotIn(List<Short> values) {
            addCriterion("NYUSEN_TOSU not in", values, "nyusenTosu");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuBetween(Short value1, Short value2) {
            addCriterion("NYUSEN_TOSU between", value1, value2, "nyusenTosu");
            return (Criteria) this;
        }

        public Criteria andNyusenTosuNotBetween(Short value1, Short value2) {
            addCriterion("NYUSEN_TOSU not between", value1, value2, "nyusenTosu");
            return (Criteria) this;
        }

        public Criteria andTenkoIsNull() {
            addCriterion("TENKO is null");
            return (Criteria) this;
        }

        public Criteria andTenkoIsNotNull() {
            addCriterion("TENKO is not null");
            return (Criteria) this;
        }

        public Criteria andTenkoEqualTo(String value) {
            addCriterion("TENKO =", value, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoNotEqualTo(String value) {
            addCriterion("TENKO <>", value, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoGreaterThan(String value) {
            addCriterion("TENKO >", value, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoGreaterThanOrEqualTo(String value) {
            addCriterion("TENKO >=", value, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoLessThan(String value) {
            addCriterion("TENKO <", value, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoLessThanOrEqualTo(String value) {
            addCriterion("TENKO <=", value, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoLike(String value) {
            addCriterion("TENKO like", value, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoNotLike(String value) {
            addCriterion("TENKO not like", value, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoIn(List<String> values) {
            addCriterion("TENKO in", values, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoNotIn(List<String> values) {
            addCriterion("TENKO not in", values, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoBetween(String value1, String value2) {
            addCriterion("TENKO between", value1, value2, "tenko");
            return (Criteria) this;
        }

        public Criteria andTenkoNotBetween(String value1, String value2) {
            addCriterion("TENKO not between", value1, value2, "tenko");
            return (Criteria) this;
        }

        public Criteria andZenhan3fIsNull() {
            addCriterion("ZENHAN_3F is null");
            return (Criteria) this;
        }

        public Criteria andZenhan3fIsNotNull() {
            addCriterion("ZENHAN_3F is not null");
            return (Criteria) this;
        }

        public Criteria andZenhan3fEqualTo(BigDecimal value) {
            addCriterion("ZENHAN_3F =", value, "zenhan3f");
            return (Criteria) this;
        }

        public Criteria andZenhan3fNotEqualTo(BigDecimal value) {
            addCriterion("ZENHAN_3F <>", value, "zenhan3f");
            return (Criteria) this;
        }

        public Criteria andZenhan3fGreaterThan(BigDecimal value) {
            addCriterion("ZENHAN_3F >", value, "zenhan3f");
            return (Criteria) this;
        }

        public Criteria andZenhan3fGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ZENHAN_3F >=", value, "zenhan3f");
            return (Criteria) this;
        }

        public Criteria andZenhan3fLessThan(BigDecimal value) {
            addCriterion("ZENHAN_3F <", value, "zenhan3f");
            return (Criteria) this;
        }

        public Criteria andZenhan3fLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ZENHAN_3F <=", value, "zenhan3f");
            return (Criteria) this;
        }

        public Criteria andZenhan3fIn(List<BigDecimal> values) {
            addCriterion("ZENHAN_3F in", values, "zenhan3f");
            return (Criteria) this;
        }

        public Criteria andZenhan3fNotIn(List<BigDecimal> values) {
            addCriterion("ZENHAN_3F not in", values, "zenhan3f");
            return (Criteria) this;
        }

        public Criteria andZenhan3fBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZENHAN_3F between", value1, value2, "zenhan3f");
            return (Criteria) this;
        }

        public Criteria andZenhan3fNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZENHAN_3F not between", value1, value2, "zenhan3f");
            return (Criteria) this;
        }

        public Criteria andKohan3fIsNull() {
            addCriterion("KOHAN_3F is null");
            return (Criteria) this;
        }

        public Criteria andKohan3fIsNotNull() {
            addCriterion("KOHAN_3F is not null");
            return (Criteria) this;
        }

        public Criteria andKohan3fEqualTo(BigDecimal value) {
            addCriterion("KOHAN_3F =", value, "kohan3f");
            return (Criteria) this;
        }

        public Criteria andKohan3fNotEqualTo(BigDecimal value) {
            addCriterion("KOHAN_3F <>", value, "kohan3f");
            return (Criteria) this;
        }

        public Criteria andKohan3fGreaterThan(BigDecimal value) {
            addCriterion("KOHAN_3F >", value, "kohan3f");
            return (Criteria) this;
        }

        public Criteria andKohan3fGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("KOHAN_3F >=", value, "kohan3f");
            return (Criteria) this;
        }

        public Criteria andKohan3fLessThan(BigDecimal value) {
            addCriterion("KOHAN_3F <", value, "kohan3f");
            return (Criteria) this;
        }

        public Criteria andKohan3fLessThanOrEqualTo(BigDecimal value) {
            addCriterion("KOHAN_3F <=", value, "kohan3f");
            return (Criteria) this;
        }

        public Criteria andKohan3fIn(List<BigDecimal> values) {
            addCriterion("KOHAN_3F in", values, "kohan3f");
            return (Criteria) this;
        }

        public Criteria andKohan3fNotIn(List<BigDecimal> values) {
            addCriterion("KOHAN_3F not in", values, "kohan3f");
            return (Criteria) this;
        }

        public Criteria andKohan3fBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("KOHAN_3F between", value1, value2, "kohan3f");
            return (Criteria) this;
        }

        public Criteria andKohan3fNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("KOHAN_3F not between", value1, value2, "kohan3f");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_race_shosai
     *
     * @mbggenerated do_not_delete_during_merge Thu May 02 12:36:46 GMT+09:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_race_shosai
     *
     * @mbggenerated Thu May 02 12:36:46 GMT+09:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}