package com.example.entity;

import com.example.entity.LvdRaceResult;
import com.example.entity.LvdRaceResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LvdRaceResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    int countByExample(LvdRaceResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    int deleteByExample(LvdRaceResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    int deleteByPrimaryKey(String raceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    int insert(LvdRaceResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    int insertSelective(LvdRaceResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    List<LvdRaceResult> selectByExample(LvdRaceResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    LvdRaceResult selectByPrimaryKey(String raceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    int updateByExampleSelective(@Param("record") LvdRaceResult record, @Param("example") LvdRaceResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    int updateByExample(@Param("record") LvdRaceResult record, @Param("example") LvdRaceResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    int updateByPrimaryKeySelective(LvdRaceResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvd_race_result
     *
     * @mbggenerated Thu May 02 12:32:56 GMT+09:00 2019
     */
    int updateByPrimaryKey(LvdRaceResult record);
}