package com.example.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ViewRaceShosai {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_race_shosai.TOKUBETSU_KYOSO_BANGO
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    private String tokubetsuKyosoBango;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_race_shosai.KACHIUMA_BAMEI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    private String kachiumaBamei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_race_shosai.DATA_KUBUN
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    private String dataKubun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_race_shosai.RACE_CODE
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    private String raceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_race_shosai.KAISAI_NENGAPPI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    private Date kaisaiNengappi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_race_shosai.KEIBAJO_CODE
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    private String keibajoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_race_shosai.KYOSOMEI_HONDAI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    private String kyosomeiHondai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_race_shosai.AVE_3F
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    private BigDecimal ave3f;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_race_shosai.RPCI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    private BigDecimal rpci;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_race_shosai.SRun_row
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    private BigDecimal srunRow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_race_shosai.TOKUBETSU_KYOSO_BANGO
     *
     * @return the value of view_race_shosai.TOKUBETSU_KYOSO_BANGO
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public String getTokubetsuKyosoBango() {
        return tokubetsuKyosoBango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_race_shosai.TOKUBETSU_KYOSO_BANGO
     *
     * @param tokubetsuKyosoBango the value for view_race_shosai.TOKUBETSU_KYOSO_BANGO
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public void setTokubetsuKyosoBango(String tokubetsuKyosoBango) {
        this.tokubetsuKyosoBango = tokubetsuKyosoBango;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_race_shosai.KACHIUMA_BAMEI
     *
     * @return the value of view_race_shosai.KACHIUMA_BAMEI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public String getKachiumaBamei() {
        return kachiumaBamei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_race_shosai.KACHIUMA_BAMEI
     *
     * @param kachiumaBamei the value for view_race_shosai.KACHIUMA_BAMEI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public void setKachiumaBamei(String kachiumaBamei) {
        this.kachiumaBamei = kachiumaBamei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_race_shosai.DATA_KUBUN
     *
     * @return the value of view_race_shosai.DATA_KUBUN
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public String getDataKubun() {
        return dataKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_race_shosai.DATA_KUBUN
     *
     * @param dataKubun the value for view_race_shosai.DATA_KUBUN
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public void setDataKubun(String dataKubun) {
        this.dataKubun = dataKubun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_race_shosai.RACE_CODE
     *
     * @return the value of view_race_shosai.RACE_CODE
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public String getRaceCode() {
        return raceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_race_shosai.RACE_CODE
     *
     * @param raceCode the value for view_race_shosai.RACE_CODE
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public void setRaceCode(String raceCode) {
        this.raceCode = raceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_race_shosai.KAISAI_NENGAPPI
     *
     * @return the value of view_race_shosai.KAISAI_NENGAPPI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public Date getKaisaiNengappi() {
        return kaisaiNengappi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_race_shosai.KAISAI_NENGAPPI
     *
     * @param kaisaiNengappi the value for view_race_shosai.KAISAI_NENGAPPI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public void setKaisaiNengappi(Date kaisaiNengappi) {
        this.kaisaiNengappi = kaisaiNengappi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_race_shosai.KEIBAJO_CODE
     *
     * @return the value of view_race_shosai.KEIBAJO_CODE
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public String getKeibajoCode() {
        return keibajoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_race_shosai.KEIBAJO_CODE
     *
     * @param keibajoCode the value for view_race_shosai.KEIBAJO_CODE
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public void setKeibajoCode(String keibajoCode) {
        this.keibajoCode = keibajoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_race_shosai.KYOSOMEI_HONDAI
     *
     * @return the value of view_race_shosai.KYOSOMEI_HONDAI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public String getKyosomeiHondai() {
        return kyosomeiHondai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_race_shosai.KYOSOMEI_HONDAI
     *
     * @param kyosomeiHondai the value for view_race_shosai.KYOSOMEI_HONDAI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public void setKyosomeiHondai(String kyosomeiHondai) {
        this.kyosomeiHondai = kyosomeiHondai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_race_shosai.AVE_3F
     *
     * @return the value of view_race_shosai.AVE_3F
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public BigDecimal getAve3f() {
        return ave3f;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_race_shosai.AVE_3F
     *
     * @param ave3f the value for view_race_shosai.AVE_3F
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public void setAve3f(BigDecimal ave3f) {
        this.ave3f = ave3f;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_race_shosai.RPCI
     *
     * @return the value of view_race_shosai.RPCI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public BigDecimal getRpci() {
        return rpci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_race_shosai.RPCI
     *
     * @param rpci the value for view_race_shosai.RPCI
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public void setRpci(BigDecimal rpci) {
        this.rpci = rpci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_race_shosai.SRun_row
     *
     * @return the value of view_race_shosai.SRun_row
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public BigDecimal getSrunRow() {
        return srunRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_race_shosai.SRun_row
     *
     * @param srunRow the value for view_race_shosai.SRun_row
     *
     * @mbggenerated Tue Jan 29 22:27:59 GMT+09:00 2019
     */
    public void setSrunRow(BigDecimal srunRow) {
        this.srunRow = srunRow;
    }
}